// Bespoke, per-card seller takeaway — the "so what" that leads every reveal.
//
// This is the single most important line a player should walk away with: the
// transferable selling principle behind the card, NOT a restatement of the
// buyer-facing reframe. Keyed by card id (family letter + 1-based index, e.g.
// "A7"), matching the ids the generator assigns. Every card must have one —
// the content pipeline + validator fail the build if any id is missing.
//
// Voice: crisp, memorable, second-person/imperative, ~10–20 words. Each should
// be genuinely distinct so no two reveals feel the same.

export default {
  // A — Mainframe / COBOL core
  A1: "Fear guards every legacy core. Start read-only: understanding before surgery is what earns the first yes.",
  A2: "When a rewrite feels impossibly huge, shrink the ask — one bounded, measurable slice beats an eight-figure leap of faith.",
  A3: "Key-person risk is a countdown, not a maybe. Sell the urgency of capturing logic before the last expert walks out.",
  A4: "Don't pitch new governance. Show the agent riding existing controls: reviewable PRs, same gates, nothing new to trust.",
  A5: "When the workarounds become the problem, sell the map first — you can't safely change what nobody can see.",
  A6: "Never argue capability. Let skeptics test it on a module they know cold and judge the output themselves.",
  A7: "'Too central to touch' is the opening, not the objection — read-only documentation changes nothing and earns entry.",
  A8: "A black box everyone fears is a documentation sale. Trace the job chains before the 2am call finds no one.",
  A9: "What's tedious for humans is tractable for agents. Reframe 'too low-level' as exactly why they need the help.",
  A10: "In risk-averse shops, safety is the yes you're selling — lead with 'understand before you change,' not speed.",
  A11: "Niche stacks aren't the blocker. The sale is capturing logic before a retiring operator base takes it with them.",
  A12: "Fear of the unknown freezes the core. Sell the impact map that finally answers 'what breaks if I change this?'",
  A13: "The problem often isn't the COBOL — it's the data nobody tracks. Sell lineage where humans already gave up.",
  A14: "If the target keeps moving, sell continuous re-sync, not a frozen snapshot — that's why past migrations never converged.",
  A15: "Separate the cost of doing business from waste. Some compute growth is inefficiency an agent can find and cut.",
  A16: "A new UI over an old core still inherits its limits. Sell modernization that reaches the real constraint.",
  A17: "When no one can draw the flow end to end, that's the sale — agents stitch scattered logic into one picture.",
  A18: "Don't sell the program, sell the proof. One cheap slice with real numbers builds the case leadership will fund.",
  A19: "Shift the cost story: one reviewer over agent output, not a team of premium contractors doing the grind.",
  A20: "Every bespoke integration is a recurring tax. Sell the reusable layer, not another one-off you'll pay for again.",
  A21: "Recurring audit pain is durable value — agent-drafted, human-signed docs turn re-explaining into standing evidence.",
  A22: "Under a merger clock, speed of understanding is the sale — document both cores in parallel so the call isn't a guess.",
  A23: "'Always overruns' really means 'always big-bang.' Sell the inverted shape: one measured slice before any commitment.",
  A24: "Don't ask for new access. Show the agent as a scoped, audited identity inside controls that already exist.",
  A25: "Threatened experts sink deals quietly. Sell elevation — they direct and review while the agent takes the grind.",
  A26: "Past burn is skepticism, not a no. Distinguish reasoning from static analysis, then let them test it on known code.",
  A27: "'Too sensitive to change' means sell understanding first — document the rules read-only before anyone contemplates an edit.",
  A28: "Unfashionable models still run the business. Sell capturing the logic now, before the last person who gets it leaves.",
  A29: "Heavy ceremony is distrust of the code in disguise. Restore understanding and tests, and the process can safely shrink.",
  A30: "Cross-language black boxes are an agent's strength, not its limit — sell tracing the boundaries humans can't follow.",
  A31: "A date without a plan is hope. Sell the year-one first slice that makes the five-year target actually credible.",
  A32: "When specs and code disagree, the code wins. Sell extracting the real rules before that understanding is lost.",
  A33: "'It works' masks a countdown. Sell acting now, cheaply, versus acting later in a crisis at a premium.",
  A34: "No vendor safety net means all the risk is theirs. Sell reconstructing the customizations so they can own it.",
  A35: "If it always loses to revenue work, remove the trade-off — agents add capacity so modernization stops competing.",
  A36: "The most critical system is often the most fragile. Sell documenting the switch logic before a failure forces it.",
  A37: "Fragmented contractor knowledge is a liability you rent. Sell consolidating it into one shared base you own.",
  A38: "You can't offload what you can't see. Sell documenting the data so reporting moves to cheaper platforms safely.",
  A39: "Win the board by changing the words: not 'AI touches the core' but 'a scoped contributor passing every gate.'",
  A40: "Reconciliation burden is a symptom of opaque data. Sell documenting the source so the burden shrinks or vanishes.",
  A41: "Funding follows momentum. Sell a quick, documented, working first slice to keep the initiative alive past the first review.",
  A42: "Batch limits are business limits. Sell documenting the batch logic as the first concrete step toward real-time.",
  A43: "Outsourcing hollowed out your leverage. Sell rebuilding internal understanding through documentation you control.",
  A44: "Flip the risk frame: a read-only pilot has near-zero downside; the real risk is the unmanaged status quo.",
  A45: "Docs rot the moment they're written. Sell regeneration from current code, not another document that decays.",
  A46: "Slow diagnosis is untraced control flow. Sell the trace that turns hours of debugging into minutes.",
  A47: "Dying hardware is a hard deadline nobody sets on purpose. Sell documenting the system so it can move off in time.",
  A48: "New products stall on batch access. Sell documenting the paths that let you build a real-time layer over the core.",
  A49: "A burned CIO wants evidence, not promises. Sell a bounded pilot with one clear success metric they pick.",

  // B — Framework version lag
  B1: "Upgrades are mechanical, verifiable, and parallel — sell a fleet doing every repo at once while engineers just approve.",
  B2: "You can't standardize what you haven't counted. Sell the estate-wide inventory before the fix.",
  B3: "A stalled runtime migration moves the moment translation is automated and tested — sell removing the manual bottleneck.",
  B4: "The difference between dumping work and reducing it is verification — sell green, reviewable PRs, not a pile of diffs.",
  B5: "EOL isn't a someday problem. Sell the version-by-version climb to a supported release, verified at each step.",
  B6: "Dependency conflicts are where upgrades die. Sell diagnosing the root conflict, not just bumping numbers.",
  B7: "A dead framework in production is silent risk. Sell doing the heavy mechanical migration while the team reviews.",
  B8: "Lock-in feels permanent until the migration is cheap. Sell moving off .NET Framework across the whole estate at once.",
  B9: "Legacy patterns spread by copy-paste. Sell mechanically converting them everywhere, not one component at a time by hand.",
  B10: "A major-version cliff is climbed component by component. Sell systematic, verified steps over a scary all-at-once jump.",
  B11: "jQuery dependence is a slow leak. Sell replacing the patterns incrementally so nothing breaks on the way out.",
  B12: "Upgrades always lose to features because they share the same team. Sell capacity that doesn't compete with the roadmap.",
  B13: "Version sprawl is an alignment problem, not a rewrite. Sell aligning the whole monorepo in parallel.",
  B14: "An internal fork is a tax you forgot you're paying. Sell reconciling with upstream so you can finally drop it.",
  B15: "Extreme lag is many jumps, each with its own breaking changes. Sell stepping through them sequentially, verified.",
  B16: "Never upgrade without a net. Sell adding the missing coverage first, then upgrading against real tests.",
  B17: "Painful batches happen because currency isn't continuous. Sell keeping dependencies current in the background instead.",
  B18: "A stale stack is a recruiting handicap you can measure in offers declined. Sell the move to a modern LTS.",
  B19: "Opaque build tooling blocks everything downstream. Sell documenting the config, then migrating it incrementally.",
  B20: "A store deadline is leverage, not a threat. Sell driving the SDK migration to hit it with deprecated APIs handled.",
  B21: "Broad, repetitive, cross-cutting changes are exactly what agents scale — sell the pervasive-dependency upgrade at once.",
  B22: "Backlash comes from naive automation. Sell the agent that builds, fixes regressions, and surfaces only green PRs.",
  B23: "Frame upgrades as cheap continuous insurance the agent makes near-free — versus expensive crisis remediation later.",
  B24: "Delegation resistance melts when seniors keep the judgment. Sell them directing while the agent does the bulk.",
  B25: "Manual upgrades miss the subtle regressions. Sell coverage around the change that catches what eyes don't.",
  B26: "Abandoned dependencies don't get safer with time. Sell upgrading the framework and swapping in maintained equivalents.",
  B27: "Behavior-dependent lag hides landmines. Sell finding every dependence on changed behavior and adapting it under test.",
  B28: "Betting on a fading ecosystem compounds. Sell making the eventual migration affordable and incremental now, not later.",
  B29: "Version divergence breaks at the seams. Sell realigning both sides toward compatible, current tooling in parallel.",
  B30: "When a version blocks a feature, the upgrade is feature work. Sell it as unblocking revenue, not housekeeping.",
  B31: "A stale UI framework ages the whole product. Sell migrating it and modernizing the component patterns incrementally.",
  B32: "A provider cutoff is a wall with a date on it. Sell upgrading the runtime and fixing incompatibilities before it hits.",
  B33: "Sunk cost keeps teams stuck. Sell making the move cheap enough that ongoing lag cost clearly outweighs it.",
  B34: "A lagging foundation library holds every consumer hostage. Sell upgrading it and propagating to all of them.",
  B35: "API coupling makes upgrades scary. Sell decoupling and upgrading while preserving behavior under test.",
  B36: "An EOL language drags stale plugins with it. Sell upgrading the runtime and modernizing or replacing the plugins.",
  B37: "Deprecated test tooling quietly rots your safety net. Sell migrating the suite and converting the tests as you go.",
  B38: "Fragmented internal libraries multiply maintenance. Sell rolling the current version across services and fixing call sites.",
  B39: "Architects fear losing intent. Sell the agent upgrading within their constraints and flagging conflicts for review.",
  B40: "A dependency freeze only grows the wall. Sell incremental, tested upgrades so it never has to be scaled all at once.",
  B41: "An officially deprecated dependency has a named successor. Sell executing the recommended migration everywhere.",
  B42: "Removed platform APIs break at launch, not before. Sell finding every use and migrating manifests to current equivalents.",
  B43: "Estate-wide lag is a scale problem manual effort can't win. Sell continuous currency across the whole estate.",
  B44: "Rollback scars make teams upgrade-shy. Sell stronger coverage so problems surface in CI, not in production.",
  B45: "A broken toolchain blocks the upgrades it should enable. Sell modernizing CI first, then the dependencies it builds.",
  B46: "Leadership can't fund invisible lag. Sell the version-currency metric that makes the risk legible and fundable.",

  // C — Language / platform migration
  C1: "Split the work: agents do the repetitive translation, humans own architecture — the Itaú pattern, 59 services to 9.",
  C2: "Don't boil the ocean. Sell one proven pilot, then a fleet running the estate in parallel — not a big-bang rewrite.",
  C3: "A forced platform exit is a deadline you can use. Sell accelerating the migration and de-risking the date.",
  C4: "Close the trust deficit with proof — a bounded slice, an agreed metric, verification built into every step.",
  C5: "A monolith yields to mapping, not machetes. Sell dependency-mapped, incremental extraction against a verifiable target.",
  C6: "Re-platforming is repetitive adaptation at scale. Sell doing it in parallel while the team steers the design.",
  C7: "Slow translation is the whole delay. Sell parallel agents doing it while engineers own the architecture.",
  C8: "Stored-procedure logic is where migrations hide. Sell translating it and verifying behavior against the source.",
  C9: "A cloud mandate without capacity just stalls. Sell the execution that turns it into measurable progress.",
  C10: "Save your best people for the new design. Sell agents taking the repetitive porting off their plate.",
  C11: "Toolchain migrations die in the edge cases. Sell handling them and rebuilding the automation on the new platform.",
  C12: "Never migrate blind. Sell documenting the source behavior first, then migrating against that verified spec.",
  C13: "Data-model change is the risky half of migration. Sell building and verifying the transform mappings alongside the code.",
  C14: "When the original team left mid-migration, sell reconstructing its state and decisions from the code, then finishing.",
  C15: "Verification is the real bottleneck. Sell auto-generated tests that clear converted modules without a human queue.",
  C16: "Migration burns out your seniors. Sell agents taking the repetitive porting so they return to work that keeps them.",
  C17: "Per-service migration is a pattern applied N times. Sell running that consistent pattern across all of them at once.",
  C18: "A renewal price hike is a deadline. Sell accelerating the vendor exit to beat it before the increase lands.",
  C19: "'We can't estimate it' is solvable. Sell analyzing the source to produce a grounded scope, not a guess.",
  C20: "You can't decompose what you can't see. Sell mapping the monolith's real dependencies to reveal natural boundaries.",
  C21: "A quality-deficit trust gap closes with verification. Sell checking migrated behavior against the source at each step.",
  C22: "Let humans keep the novel decisions. Sell the agent taking the repetitive majority under review — that's the split.",
  C23: "Freezing until crisis is the riskier path. Sell incremental, verified migration as the lower-risk alternative.",
  C24: "A long parallel run bleeds money. Sell shortening the migration so that expensive window closes sooner.",
  C25: "Without equivalence checks, regressions slip through. Sell automated old-vs-new output comparison at every step.",
  C26: "Obscure source languages aren't a dead end. Sell agents reading and translating them where human expertise is gone.",
  C27: "Scope creep comes from discovering the finish line late. Sell inventorying the full scope up front so it's defined.",
  C28: "Three acquired systems is a consolidation, not three migrations. Sell mapping the overlaps and driving onto one target.",
  C29: "Fixed-price buyers fear the unknown. Sell one bounded slice at a fixed price to calibrate the rest with data.",
  C30: "ETL logic is dense and undocumented. Sell documenting and translating it to the new platform at scale.",
  C31: "Scientific code demands precision. Sell translating the numerical logic and verifying results match to the digit.",
  C32: "Cutover risk lives in sync and reconciliation. Sell building and verifying that logic to de-risk the switch.",
  C33: "Long programs die with the sponsor. Sell early, durable, incremental results that survive leadership churn.",
  C34: "Understanding doesn't require typing it all by hand. Sell gaining it through reviewing generated changes, faster.",
  C35: "An unstable target churns your work. Sell agents adapting migrated code quickly as the target settles.",
  C36: "Zero-downtime is a design, not a wish. Sell helping design and verify the incremental, no-downtime path.",
  C37: "Containerization fails on hidden assumptions. Sell finding and fixing them across the whole app estate.",

  // D — Undocumented tribal knowledge
  D1: "Tribal knowledge is a single point of failure. Sell the docs and tests that make an opaque system legible.",
  D2: "You can't change safely without a net. Sell writing the missing coverage as you modernize, unlocking safe change.",
  D3: "Opacity is why onboarding drags. Sell generated docs and consistent patterns that compress ramp time.",
  D4: "Docs written once drift into fiction. Sell generating them from the actual current code so they reflect reality.",
  D5: "Refactoring blind is a gamble. Sell tracing and mapping dependencies so change becomes informed, not risky.",
  D6: "Deploy knowledge in one head is an outage waiting to happen. Sell a runbook anyone can follow.",
  D7: "An expert's last day is a deadline. Sell capturing their architectural knowledge from the code before it's gone.",
  D8: "Mystery config is fear you touch nothing. Sell tracing where each flag is used and documenting its real effect.",
  D9: "Cargo-cult code persists because no one dares explain it. Sell analysis that lets you change it with understanding.",
  D10: "Runbooks decay silently. Sell regenerating current ones from the actual system so ops stops flying blind.",
  D11: "A platform-knowledge monopoly bottlenecks every team. Sell documenting it so consumers self-serve safely.",
  D12: "You can't scope what you don't understand. Sell documenting the system so work can be estimated before it's started.",
  D13: "Months of shadowing is a knowledge tax. Sell generated docs that compress the ramp dramatically.",
  D14: "Incident diagnosis is slow when the system is a mystery. Sell the documentation that shortens time-to-cause.",
  D15: "The cost objection ignores who does the work. Sell the agent drafting docs while the expert reviews, not authors.",
  D16: "When knowledge is job security, reframe it — sell documentation as elevating experts to leaders, not diminishing them.",
  D17: "Implicit data assumptions cause silent corruption. Sell surfacing and documenting them before they bite.",
  D18: "An orphaned critical artifact is a landmine. Sell analyzing and documenting it so it can be maintained or replaced.",
  D19: "Business rules buried in code disappear with it. Sell extracting and documenting them before any refactor.",
  D20: "A test suite nobody understands gives meaningless failures. Sell documenting what each test actually verifies.",
  D21: "Documentation loses to delivery every time. Sell making it cheap enough that it stops being a trade-off.",
  D22: "An integration only a vendor understands is captive risk. Sell documenting the logic to bring it in-house.",
  D23: "Teams rebuild what they can't find. Sell documenting and indexing existing capabilities so they reuse instead.",
  D24: "Cryptic error codes waste every on-call. Sell documenting them and their causes into a usable reference.",
  D25: "'Docs might be wrong' misses the baseline. Sell reviewed generated docs as more accurate than tribal memory.",
  D26: "Unverifiable controls fail audits. Sell documenting where and how they're implemented as durable evidence.",
  D27: "Operational glue scattered across scripts is invisible risk. Sell discovering and mapping it into one picture.",
  D28: "Dispersed ownership means no one holds the whole. Sell reconstructing a coherent, whole-system understanding.",
  D29: "Bus-factor risk is concentrated knowledge. Sell documenting what key people hold to spread it and cut the risk.",
  D30: "Accidental API behaviors become contracts consumers depend on. Sell documenting the de facto contract before you change it.",
  D31: "'Our system is unique' is testable. Sell proving accuracy on a module the team knows and letting them judge.",
  D32: "Authorization logic you can't reason about can't be trusted. Sell mapping and documenting it so access is auditable.",
  D33: "You can't focus effort on an unknown footprint. Sell usage analysis that separates live, dormant, and dead code.",
  D34: "A DR plan assumes knowledge no one wrote down. Sell documenting it so recovery is executable by anyone.",
  D35: "Special-case business exceptions live only in veterans' heads. Sell surfacing each one from the code.",
  D36: "You can't retire a system with unknown dependencies. Sell tracing every one so it can actually be sunset.",

  // E — Technical-debt drag
  E1: "Debt is code that slows developers down. Sell attacking it continuously and in parallel — the Project Coral framing.",
  E2: "Inconsistency compounds. Sell applying consistent patterns across the estate at a scale humans can't sustain by hand.",
  E3: "Dead code carries risk with no upside. Sell tracing usage and removing it safely, with tests confirming nothing breaks.",
  E4: "Deferring debt forever is a decision, not a delay. Sell continuous background paydown that doesn't touch feature capacity.",
  E5: "Slow builds tax every developer, every day. Sell optimizing the pipeline to restore fast feedback.",
  E6: "Debt tools that only report disappoint. Sell agents that do the remediation and let you measure the outcome.",
  E7: "Duplication multiplies every future change. Sell finding and consolidating it across the codebase.",
  E8: "God functions are untestable and unchangeable. Sell breaking them down incrementally with tests confirming behavior.",
  E9: "Every sprint adds debt. Sell continuous paydown in the background that offsets what accrues.",
  E10: "A felt slowdown has concrete causes. Sell attacking the real debt behind it so improvement becomes measurable.",
  E11: "Inconsistent error handling breaks unpredictably. Sell standardizing it to one predictable strategy.",
  E12: "Coverage debt makes every change slow and scary. Sell writing the missing tests so verification is automated.",
  E13: "You can't act on debt you haven't counted. Sell inventorying it into concrete, prioritized items leadership can fund.",
  E14: "Every workaround is a recurring tax. Sell removing the debt that forces them, freeing capacity for real work.",
  E15: "Debt hurts most where code churns. Sell prioritizing paydown there for the biggest velocity return.",
  E16: "Invisible work loses the budget fight. Sell debt paydown that's continuous and cheap, so it never competes with features.",
  E17: "Architects fear losing pattern control. Sell the agent conforming to their target patterns and flagging conflicts.",
  E18: "Broken logging means you're operating blind. Sell standardizing it so observability actually works.",
  E19: "Coupling makes every change cascade. Sell identifying and reducing it so changes stay contained.",
  E20: "Debt sprints never keep up. Sell continuous paydown instead of a periodic effort that always loses ground.",
  E21: "Schema accretes unused cruft. Sell usage analysis that identifies and safely retires it.",
  E22: "Debt fatalism breaks with proof. Sell fixing one painful, high-churn area so the team sees improvement is possible.",
  E23: "Flaky tests destroy CI trust. Sell diagnosing and fixing them so green means green again.",
  E24: "Performance debt is death by a thousand cuts. Sell systematically finding and fixing the small inefficiencies.",
  E25: "Docs drifting from code mislead everyone. Sell reconciling them with real behavior and keeping them current.",
  E26: "Convention drift fragments a codebase. Sell converging it on the current standard consistently.",
  E27: "IaC that doesn't match reality is dangerous. Sell reconciling it so it becomes trustworthy again.",
  E28: "Stale feature flags hide dead branches. Sell identifying and removing them safely.",
  E29: "Reframe debt paydown as recovered delivery capacity — measurable velocity that funds itself.",
  E30: "Rising feature cost is debt in disguise. Sell reducing it to restore predictable delivery.",
  E31: "A deferred-fix backlog is known, scoped work. Sell working through it systematically to clear it.",
  E32: "Cross-service duplication means fixing the same bug N times. Sell consolidating or propagating fixes consistently.",
  E33: "Not all debt matters equally. Sell assessing it by churn, complexity, and risk to prioritize what actually counts.",
  E34: "Warning blindness buries real signals. Sell clearing the backlog so new warnings get noticed and fixed.",
  E35: "Concurrency debt causes the scariest bugs. Sell documenting the patterns and adding tests around them.",

  // F — Compliance-forced modernization
  F1: "Compliance work is mandatory and low-glory. Sell making it dramatically cheaper and faster than doing it by hand.",
  F2: "Traceability mandates need evidence across systems. Sell analyzing and documenting the data flows to produce it.",
  F3: "Accountability isn't lost to automation. Sell the agent proposing and a named human approving through existing control.",
  F4: "M&A integration runs on an unforgiving clock. Sell documenting the unfamiliar codebase and accelerating the work.",
  F5: "A regulatory retrofit across hundreds of screens is repetitive at scale — sell applying it consistently in parallel.",
  F6: "PCI scope is every system touching card data. Sell inventorying them all and applying the changes consistently.",
  F7: "SOX needs traceability you can evidence. Sell implementing it and generating the audit proof the controls require.",
  F8: "Right-to-erasure means knowing where personal data lives. Sell mapping it across systems and implementing compliant deletion.",
  F9: "DORA demands resilience you can document. Sell mapping dependencies and implementing the evidence it requires.",
  F10: "Manual evidence assembly repeats every cycle. Sell generating it directly from the systems so audits get cheap.",
  F11: "You can't assess compliance on opaque code. Sell documenting the systems first, then remediating the gaps.",
  F12: "A deadline gated by understanding slips. Sell compressing the understanding phase so remediation starts sooner.",
  F13: "Each mandate becomes a fresh fire drill. Sell a reusable remediation capability so the next one isn't.",
  F14: "Segregation of duties must be demonstrable. Sell documenting and implementing the controls that prove it.",
  F15: "'Only humans can be trusted' still holds — sell the agent proposing while a named human approves through existing controls.",
  F16: "Compliance framed as pure cost loses. Sell the dramatic savings plus reuse of the modernized systems beyond compliance.",
  F17: "Data residency means knowing where data actually sits. Sell tracing flows and flagging non-compliant placement.",
  F18: "Certification is the price of market access. Sell remediating the codebase to meet it faster.",
  F19: "Annual heroic compliance isn't sustainable. Sell making it a repeatable, automated process instead.",
  F20: "An encryption mandate means finding every unencrypted store. Sell identifying and encrypting them across the estate.",
  F21: "The agent isn't a new compliance surface. Sell it operating within existing controls as a scoped, auditable identity.",
  F22: "Multi-jurisdiction rule changes multiply the work. Sell applying each consistently across every variant and verifying.",
  F23: "A protocol deprecation is a hard cutoff. Sell finding every use and migrating to the compliant replacement.",
  F24: "Inconsistent audit logging leaves gaps. Sell standardizing it across systems to close them.",
  F25: "Disruption-averse leaders fear compliance change. Sell incremental, verified work that lands without breaking the business.",
  F26: "Model-risk rules demand documented behavior. Sell documenting the models' logic to satisfy them.",
  F27: "Automated, auditable controls are more rigorous than manual effort — sell that as the opposite of cutting corners.",
  F28: "Supply-chain compliance starts with an inventory. Sell cataloguing dependencies, assessing status, and remediating.",
  F29: "A compliance backlog outpacing the team is a capacity problem. Sell adding remediation capacity so it stops growing.",
  F30: "Accessibility is now a legal mandate. Sell remediating the failures across all pages consistently and at scale.",
  F31: "Access-logging mandates need consistency. Sell implementing uniform logging and retention across systems in scope.",
  F32: "Paper controls that aren't enforced fail audits. Sell verifying each documented control is genuinely in the code.",
  F33: "Consent management must be consistent across apps. Sell implementing capture and enforcement uniformly.",
  F34: "Sign-off overhead multiplies with changes. Sell batching similar ones for a single review to amortize approval.",
  F35: "Data-lineage mandates need the flow traced end to end. Sell tracing it and producing the required documentation.",

  // G — Talent & hiring pressure
  G1: "Talent flees legacy grind. Sell agents carrying the maintenance load so scarce humans do work they actually want.",
  G2: "Seniors doing maintenance is misallocated talent. Sell agents absorbing it so they return to high-value creation.",
  G3: "Attrition erodes institutional knowledge. Sell capturing and documenting it before more walks out the door.",
  G4: "Replacement fear kills adoption. Frame agents as leverage on the engineers you keep — toil to them, judgment to humans.",
  G5: "Delivery shouldn't wait on hard-to-fill hires. Sell agents adding capacity now, in parallel with recruiting.",
  G6: "Juniors churn when stuck on legacy. Sell agents carrying maintenance so juniors get growth-worthy problems.",
  G7: "A dated stack loses candidates before the interview. Sell modernizing it and carrying the legacy work.",
  G8: "Growth capped by hiring is a solvable ceiling. Sell scaling engineering capacity without the hiring bottleneck.",
  G9: "A team with no slack is one absence from crisis. Sell agents as buffer capacity that absorbs the shock.",
  G10: "Attrition takes knowledge with it. Sell documenting what leavers knew and carrying the work until backfill lands.",
  G11: "You can't win every salary battle. Sell a smaller team achieving more so you depend less on out-paying rivals.",
  G12: "Toil drives your best people out. Sell agents absorbing it so engineers spend time on the work that keeps them.",
  G13: "You can't out-hire the giants. Sell agents giving a small team outsized capacity instead.",
  G14: "Headcount-threat perception stalls buy-in. Frame agents as relief and leverage for a stretched team, not replacement.",
  G15: "Hiring alone is too slow. Sell agents adding capacity immediately, complementing recruiting rather than waiting on it.",
  G16: "Experts carrying the load alone burn out. Sell agents sharing it to ease the pressure before you lose them.",
  G17: "Keep-the-lights-on saturates the team. Sell agents taking that load so people are freed for new projects.",
  G18: "Rare-skill concentration is dangerous. Sell agents documenting and carrying the niche work to break it.",
  G19: "Demoralizing onboarding drives early attrition. Sell generated docs that make ramping faster and less painful.",
  G20: "Skill-atrophy fear is backwards. Sell engineers growing into architecture and direction — higher-order, not atrophied.",
  G21: "Premium contractors are a rented crutch. Sell sustainable agent capacity that reduces the dependency.",
  G22: "The legacy team carries a stigma. Sell agents doing the grind so those roles become modernization, not dead ends.",
  G23: "Firefighting starves mentorship. Sell agents reducing the load so seniors mentor and juniors grow.",
  G24: "Reorgs erode capacity. Sell agents as a stable capacity floor organizational churn can't wipe out.",
  G25: "Your employer brand is what engineers do all day. Sell agents doing the toil so yours is where the meaningful work is.",
  G26: "Initiatives shouldn't wait on hiring lead time. Sell agents providing immediate ramp capacity.",
  G27: "Flat headcount against growing load is a widening gap. Sell agents closing it.",
  G28: "Sudden capacity loss leaves a hole. Sell agents backstopping the depleted team's workload while you rebuild.",
  G29: "A roadmap gated by staffing follows the wrong master. Sell capacity so it can follow priority instead.",
  G30: "Specialists queued on routine work is waste. Sell agents handling the routine so the queue shrinks and they focus.",
  G31: "'Needing agents admits failure' is the wrong frame. Sell them as leverage that scales a good team, like any tooling.",
  G32: "Thin on-call burns people out. Sell documented systems and diagnosis help so more people can respond.",
  G33: "No innovation capacity means no future. Sell agents freeing delivery capacity so some of the team can innovate.",
  G34: "Talent avoids the legacy work. Sell agents doing it so hires focus on what drew them in.",

  // H — Security & vulnerability exposure
  H1: "A patch backlog is remediation at scale. Sell parallel fixes — the Itaú pattern of auto-resolving most findings.",
  H2: "You can't remediate what you haven't mapped. Sell inventorying security debt, then fixing where it matters most.",
  H3: "Trust doesn't rest on the model. Sell agent output passing the same deterministic security gates as any contributor's.",
  H4: "A board security mandate needs an audit trail. Sell continuous remediation with evidence of the hardening.",
  H5: "Inherited code carries unknown risk. Sell auditing it, surfacing the risks, and remediating with a trail.",
  H6: "A CVE backlog is parallel work. Sell working it at scale, patching and verifying, not one ticket at a time.",
  H7: "Unknown blast radius is the real danger. Sell rapidly finding every affected location and patching it — the Log4Shell model.",
  H8: "Frozen-but-vulnerable dependencies are a standing risk. Sell upgrading them and fixing the breakage under test.",
  H9: "Tracked CVEs miss insecure-by-design patterns. Sell finding and remediating those across the codebase too.",
  H10: "Not every vulnerability is urgent. Sell assessing them in context to prioritize the ones that truly matter.",
  H11: "Fixing reported instances leaves the pattern. Sell fixing the root everywhere it occurs.",
  H12: "Findings that reopen aren't fixed. Sell remediating comprehensively so they close and stay closed.",
  H13: "Hardcoded secrets are exposure waiting to happen. Sell finding every one and moving them to proper management.",
  H14: "Active exploitation is a race against the clock. Sell parallelizing the patch to shrink the exposure window.",
  H15: "Security gatekeeping isn't bypassed. Sell agent changes going through the same review and approval as any engineer.",
  H16: "Reactive security fixes exposure after it's exploited. Sell proactive remediation cheap enough to do it before.",
  H17: "Inconsistent input validation is an open door. Sell auditing and standardizing it across every entry point.",
  H18: "Unsupported systems are exposure with no patch coming. Sell migrating off or hardening them.",
  H19: "Supply-chain assurance needs evidence. Sell inventorying it, remediating issues, and producing the proof.",
  H20: "Access drifts toward over-privilege. Sell mapping effective access and remediating toward least privilege.",
  H21: "'The fix might introduce risk' is why you gate it. Sell fixes going through security tests and review before release.",
  H22: "Plaintext sensitive data is a breach headline waiting. Sell finding it and implementing encryption across stores.",
  H23: "Outdated auth is a soft target. Sell modernizing it to current standards, verified against attacks.",
  H24: "A fix without a regression test invites recurrence. Sell adding checks that catch the class if it returns.",
  H25: "Pen-test findings that aren't closed are just a to-do list. Sell remediating them in parallel so they actually close.",
  H26: "Judgment stays with your CISO. Sell the agent handling the scale-out remediation under that direction.",
  H27: "Transitive dependencies are a blind spot. Sell mapping the full tree and remediating vulnerable components deep in it.",
  H28: "Customers finding your exposure is the worst case. Sell continuous scanning and remediation so you catch it first.",
  H29: "Insurance-mandated controls need evidence. Sell implementing and evidencing them across the estate.",
  H30: "Weak crypto is exposure hiding in plain sight. Sell finding it and migrating to strong, current algorithms.",
  H31: "Alert fatigue numbs response to real threats. Sell triaging and remediating the noise so genuine ones stand out.",
  H32: "A slow release path delays security fixes. Sell streamlining it so fixes ship quickly and safely.",
  H33: "Injection-prone queries are a classic breach. Sell converting them to parameterized ones across the codebase.",
  H34: "'We're covered' assumes, not measures. Sell converting spend into measurably reduced exposure, not more tools.",
  H35: "Inconsistent posture across services is a weakest-link problem. Sell applying consistent controls everywhere.",
  H36: "Cloud over-permissioning is silent risk. Sell analyzing effective permissions and tightening toward least privilege.",

  // I — Cloud cost & FinOps pressure
  I1: "Runaway spend traces back to code and resources. Sell finding the drivers and remediating the biggest wasters.",
  I2: "Over-provisioned compute is money on idle. Sell right-sizing and autoscaling so you pay for what you use.",
  I3: "No cost attribution means no accountability. Sell tagging and mapping resources to owners so cost has a home.",
  I4: "Inefficient code is a recurring bill. Sell refactoring the hot, wasteful paths so the same work costs less.",
  I5: "Lift-and-shift rarely saves. Sell incrementally re-architecting toward cloud-native patterns that actually do.",
  I6: "Egress costs hide in data movement. Sell finding the costly patterns and refactoring them to cut transfer fees.",
  I7: "Stranded commitments are prepaid waste. Sell aligning workloads to them and flagging mismatches before renewal.",
  I8: "Kubernetes defaults over-provision. Sell tuning requests, limits, and scaling to real utilization, verified under load.",
  I9: "Orphaned resources bleed money quietly. Sell inventorying the estate and safely decommissioning idle ones.",
  I10: "Cost work shouldn't stall the roadmap. Sell doing the optimization in parallel so both move.",
  I11: "A dashboard reports; it doesn't save. Sell agents implementing the recommendations it only surfaces.",
  I12: "'Cost is just scale' hides waste. Sell separating real scale cost from waste and recovering the waste at scale.",

  // J — Data & analytics modernization
  J1: "Data silos mean no single truth. Sell mapping lineage and consolidating toward a governed source.",
  J2: "Stale batch analytics lag the business. Sell modernizing pipelines toward streaming where it matters.",
  J3: "Manual data wrangling wastes analysts. Sell building the transform and cleaning pipelines so they start from clean data.",
  J4: "A legacy data model fights current needs. Sell evolving the schema with safe, verified migrations.",
  J5: "Untrusted metrics undermine every decision. Sell documenting and standardizing definitions so numbers are defensible.",
  J6: "Data-quality debt spreads downstream. Sell adding quality checks and remediation across the pipelines.",
  J7: "A stalled platform migration wastes the investment. Sell porting and validating pipelines in parallel to finish it.",
  J8: "Pipeline firefighting eats the team. Sell hardening the fragile ones and handling routine breaks so they can build.",
  J9: "A governance gap fails audits and erodes trust. Sell instrumenting lineage and governance with the evidence.",
  J10: "Pipelines only the data team understands is bus-factor risk. Sell documenting them under that team's direction.",
  J11: "A new platform still needs the migration done. Sell the cleanup and porting work any purchase can't skip.",

  // K — AI/ML adoption & readiness
  K1: "AI needs a foundation to build on. Sell documenting and modernizing it so initiatives have something to stand on.",
  K2: "Models stuck in notebooks deliver nothing. Sell the productionization path — packaging, serving, monitoring.",
  K3: "AI is only as good as its data. Sell building the cleaning and preparation pipelines it depends on.",
  K4: "A model that doesn't connect to workflows is a demo. Sell the integrations that put it to work.",
  K5: "AI without observability runs blind. Sell testing, monitoring, and guardrails so it runs with oversight.",
  K6: "Ungoverned AI sprawl is risk multiplying. Sell consistent usage standards and guardrails across teams.",
  K7: "Security won't approve AI without data controls. Sell implementing the access controls and governance they need.",
  K8: "Undetected model drift degrades silently. Sell drift detection and retraining pipelines that catch it early.",
  K9: "Not every AI ask is viable. Sell assessing feasibility against real data and systems to focus on what works.",
  K10: "'AI replaces us' fear stalls adoption. Sell agents taking toil so engineers do higher-value work — amplify, not replace.",
  K11: "AI ROI skepticism is fair. Sell small, measurable pilots that prove value before anyone scales.",

  // L — Developer experience & tooling
  L1: "A broken local setup taxes every new hire. Sell fixing, documenting, and containerizing it for one-command onboarding.",
  L2: "Slow builds waste the whole team daily. Sell optimizing them — caching, parallelization — to cut the wait.",
  L3: "Inconsistent tooling fragments the org. Sell standardizing it across repos, applying the changes consistently.",
  L4: "Small friction points add up to real drag. Sell systematically removing the ones each too minor to fix alone.",
  L5: "Flaky CI erodes trust in the signal. Sell hunting down the instability so green means green.",
  L6: "Bespoke tooling lock-in is hidden risk. Sell documenting it and modernizing or replacing it with maintainable options.",
  L7: "Environment problems are a recurring velocity tax. Sell fixing them so time goes back to building.",
  L8: "DevEx always loses to features. Sell doing the improvements in parallel so they don't compete.",
  L9: "Stale dev docs mislead the team. Sell regenerating accurate ones from the code and keeping them current.",
  L10: "'DevEx is menial' misses who benefits. Sell agents doing the groundwork so seniors get the payoff without the grind.",
  L11: "DevEx skeptics want ROI. Sell cheap improvements tied to measurable time saved.",

  // M — Integration & API sprawl
  M1: "Integration spaghetti makes every change risky. Sell mapping the web and documenting each connection first.",
  M2: "Inconsistent API design confuses consumers. Sell standardizing conventions and adding consistent wrappers.",
  M3: "A fragile external dependency propagates its breakage. Sell an adapter layer and monitoring that absorbs the shock.",
  M4: "You can't retire integrations you can't see. Sell instrumenting usage, then safely killing the dead ones.",
  M5: "Format-mismatch bugs live at the boundaries. Sell standardizing the data contracts and validating at the edges.",
  M6: "Tight coupling turns one change into a cascade. Sell decoupling with interfaces so changes stay contained.",
  M7: "No integration surface blocks every partner. Sell building an API layer over existing systems without a rewrite.",
  M8: "Undocumented APIs are guesswork for consumers. Sell generating accurate docs and specs from real behavior.",
  M9: "Integration version sprawl fragments consumers. Sell migrating them to the current version and retiring the old.",
  M10: "A platform still needs the integration work done. Sell the mapping, migration, and cleanup any purchase can't skip.",
  M11: "Integration change feels like a gamble. Sell mapping dependencies and staging changes with verification.",

  // N — Observability & reliability gaps
  N1: "Customers finding your outages first is the worst signal. Sell monitoring that detects issues before they do.",
  N2: "No diagnostic visibility means slow incidents. Sell structured logging and tracing that make causes findable fast.",
  N3: "Alert noise numbs the response. Sell tuning alerting to be meaningful so signals get the attention they deserve.",
  N4: "You can't follow an issue across services without tracing. Sell distributed tracing that spans the boundaries.",
  N5: "Unaddressed root causes mean incidents recur. Sell finding and fixing the underlying causes so they stop.",
  N6: "Unmeasured reliability can't be managed. Sell instrumenting SLOs so you run on evidence, not vibes.",
  N7: "Manual incident toil burns the on-call. Sell runbooks, diagnostic tooling, and triage help that cut it.",
  N8: "Unknown failure modes surface at the worst time. Sell resilience testing that finds the weaknesses first.",
  N9: "Fragmented observability hides the picture. Sell consolidating telemetry into one coherent view.",
  N10: "A reactive reliability stance pays after the outage. Sell cheap observability so you invest before it.",
  N11: "'Observability is clutter' until the next incident. Sell clean, consistent instrumentation that pays for itself then.",

  // O — Case Files: real customer wins (grounded in devin.ai/customers)
  // L0 Client-Zero Proof
  O1: "Sell the method, not the environment. Prove it on your own org first and you walk in with numbers, not promises.",
  O2: "Never ship a strategy you haven't run. Bring the board a two-week result, and the mandate writes itself.",
  O3: "Turn adoption into a falsifiable experiment. Let the buyer set the success bar on their own live backlog.",
  O4: "'We tried AI' means autocomplete. Reframe to end-to-end ownership and measure the capacity gain directly.",
  O5: "Value trapped in a few power users never compounds. Make delegation a tracked, teachable skill so it spreads.",
  // L1 Beachhead on the Dreaded Migration
  O6: "Land on the migration everyone dreads. Fixed teach-cost, then an army of agents scales what humans can't staff.",
  O7: "A forced compliance change is the perfect beachhead — 'done' is defined by the rules, so agents fan it everywhere.",
  O8: "Partition the mountain into thousands of sub-tasks. Parallel agents beat the estimate when each validates its own work.",
  O9: "Kill 'it'll add tech debt' at the PR level. Merge rate and coverage at your review bar is a signal you can't argue with.",
  O10: "Prove one component end to end; the rest is a replay. Tangled once becomes patterned everywhere after.",
  // L2 Bottoms-Up Land-and-Expand
  O11: "When engineers pull the tool in themselves, don't create demand — remove the access friction so the pull can spread.",
  O12: "Seats cap the spread. Pooled credits let value surface from teams you never expected, and you pay for work, not chairs.",
  O13: "When attempting is nearly free, 'should we?' debates become 'let's just try it.' Sell the collapse of decision cost.",
  O14: "If a task is too vague for an agent, it's too vague for a human. Sell the discipline of well-specified, verifiable work.",
  O15: "Every change routed through engineering becomes a queue. Let others self-serve reviewed PRs and free your engineers.",
  // L3 Top-Down Mandate + Enablement
  O16: "A mandate without enablement is shelfware. Pair exec conviction with a program that rebuilds the bottleneck function.",
  O17: "Don't A/B a compounding capability. Measure a fully-committed squad — that's the signal that justifies going all-in.",
  O18: "Make delegation measurable and you can coach it. A mandate becomes capability instead of compliance.",
  O19: "Fear kills mandates from the bottom. Sell the career upgrade — rote work to agents, people into higher-value roles.",
  O20: "Knowledge trapped in a few heads throttles everyone. Sell a living knowledge layer that regenerates with the code.",
  // L4 Win the Bake-Off
  O21: "Don't argue the claim — win the eval. Being the only tool that finishes the buyer's hardest task closes the deal.",
  O22: "Enterprise gates come before capability. Clear them all, then put the right tool on the right kind of work.",
  O23: "When velocity is noisy, measure at the PR level. A clean, direct signal unlocks the scale decision.",
  O24: "An eval win isn't ROI. Turn it into a scheduled playbook and let the return compound on a day of setup.",
  O25: "Replace brute-force review meetings with generated coverage — agents even surface conflicting requirements humans miss.",
  // L5 Ride the Industry Inflection
  O26: "Sell the moment, not the feature. When capacity stops being the constraint, launching becomes a question of intent.",
  O27: "Regulation isn't the blocker — it's where agents create the most leverage. Bounded, defined work with the audit trail intact.",
  O28: "A new product paradigm rewards speed with safety. Agents add QA layers so quality rises as velocity does.",
  O29: "Staying on legacy is the risk. Sell reallocating maintenance budget into the products that win the inflection.",
  O30: "Pace becomes the brand. An enterprise that ships at startup cadence makes rivals call to ask what changed.",
  // L6 Productize into a Partner Offering
  O31: "Package proven internal wins into a repeatable offering. Sell the methodology, and meet clients wherever they are.",
  O32: "Bespoke delivery caps a practice. Template the repeating motions into playbooks so each engagement starts ahead.",
  O33: "Buyers fund outcomes, not activity. Bundle ROI analytics so returns land in terms a board can act on.",
  O34: "A managed service without methodology is body-shopping. Differentiate on the repeatable system you proved on yourself.",
  O35: "A champion's workflow is worthless if it's stuck on one team. Make it a portable playbook and one win becomes everyone's baseline.",
};
