export default [
  {
    "tier": 3,
    "prompt": "We're migrating .NET to Java but it's been eighteen months and we're maybe halfway.",
    "pattern": "Stalled language migration",
    "rootCause": "Repetitive translation consuming scarce senior-engineer time.",
    "consequence": "Overrun, morale drain, and enormous opportunity cost on your best people.",
    "diagnostic": "How many of your strongest engineers are stuck on this instead of building new products?",
    "angle": "Agents do the repetitive translation while humans own architecture — this is the Itaú pattern: 59 .NET services rewritten to Java and consolidated to 9.",
    "objection": "A migration like this needs deep human judgment, not automation.",
    "reframe": "It needs human judgment for architecture — which is exactly where your engineers stay. The agent takes the 80% that's mechanical translation, so their judgment goes where it matters.",
    "personaShift": {
      "CFO": "stops the overrun bleed",
      "VPE": "returns senior engineers to high-value work",
      "CTO": "unsticks a strategic program",
      "CRO": "de-risks a stalled, high-stakes migration"
    }
  },
  {
    "tier": 2,
    "prompt": "Leadership wants us cloud-native but we've got 200 on-prem services and no clear path.",
    "pattern": "On-prem to cloud at scale",
    "rootCause": "Manual refactoring per service is unscalable against 200 services.",
    "consequence": "A board-level strategic initiative is blocked with no credible plan.",
    "diagnostic": "If you had to move just one service next month with zero risk, which would you pick — and why that one?",
    "angle": "Start with the bounded pilot, prove it, then run a fleet of agents across the estate in parallel.",
    "objection": "Every one of those services is different; there's no repeatable approach.",
    "reframe": "They're different in detail but similar in shape. The agent handles the per-service variation while the migration pattern stays consistent — that's what makes 200 tractable.",
    "personaShift": {
      "CTO": "delivers the cloud mandate credibly",
      "CFO": "phased, measurable spend not a blank cheque",
      "VPE": "returns senior engineers to high-value work",
      "CRO": "de-risks a stalled, high-stakes migration"
    }
  },
  {
    "tier": 1,
    "prompt": "We're stuck on a vendor platform that's being deprecated and we have to get off it.",
    "pattern": "Forced platform migration",
    "rootCause": "Vendor deprecation with a hard deadline and no in-house migration capacity.",
    "consequence": "Hard deadline, high risk, limited internal bandwidth.",
    "diagnostic": "What's the drop-dead date, and what happens to you commercially if you miss it?",
    "angle": "Agents accelerate the exit migration and de-risk hitting the deadline.",
    "objection": "We don't have the people to run a migration this size in time.",
    "reframe": "That's the point — the agent supplies the capacity you don't have, doing the repetitive migration work so your small team can supervise rather than execute.",
    "personaShift": {
      "CFO": "avoids penalty/continuity cost",
      "CTO": "hits an otherwise unhittable deadline",
      "VPE": "returns senior engineers to high-value work",
      "CRO": "de-risks a stalled, high-stakes migration"
    }
  },
  {
    "tier": 4,
    "prompt": "Last migration vendor overpromised and left us with a half-working system.",
    "pattern": "Migration trust deficit",
    "rootCause": "Prior burn from a vendor who couldn't deliver at completion.",
    "consequence": "Deep skepticism; high bar for any new modernization partner.",
    "diagnostic": "What specifically broke down last time — the scoping, the execution, or the finish?",
    "angle": "Prove it on a bounded slice with an agreed success metric before any commitment; verification is built into every step.",
    "objection": "How is this different from the vendor that burned us?",
    "reframe": "Two ways: you see verifiable output at every step — passing builds, reviewable PRs — not a black-box deliverable at the end; and we prove one bounded workflow before you commit to the program.",
    "personaShift": {
      "CRO": "verifiable, auditable at each step",
      "CFO": "outcome-based, low downside",
      "CTO": "delivers the target architecture on time",
      "VPE": "returns senior engineers to high-value work"
    }
  },
  {
    "tier": 3,
    "prompt": "We want to break our monolith into microservices but every attempt stalls.",
    "pattern": "Monolith decomposition",
    "rootCause": "Decomposition requires understanding tangled dependencies humans can't fully hold.",
    "consequence": "Repeated stalled attempts; strategic architecture goal unmet.",
    "diagnostic": "What's stalled the previous attempts — understanding the boundaries, or doing the extraction work?",
    "angle": "Agents map dependencies and do the extraction work incrementally against a verifiable target.",
    "objection": "Defining service boundaries is an architectural art, not automatable.",
    "reframe": "The boundary decisions stay with your architects — the agent does the heavy extraction and refactoring once you've drawn the lines. Art for humans, labor for the agent.",
    "personaShift": {
      "CTO": "delivers the target architecture",
      "VPE": "unblocks a repeatedly-stalled program",
      "CFO": "stops migration overrun and cost bleed",
      "CRO": "de-risks a stalled, high-stakes migration"
    }
  },
  {
    "tier": 2,
    "prompt": "We're moving to a new cloud provider and have to re-platform everything under time pressure.",
    "pattern": "Cloud re-platforming",
    "rootCause": "Provider migration requires reworking infrastructure and code under deadline.",
    "consequence": "Large-scale, time-boxed re-platforming with limited capacity.",
    "diagnostic": "What's driving the deadline — cost, contract, or strategy — and how firm is it?",
    "angle": "Agents accelerate the re-platforming and adapt code to the new environment at scale.",
    "objection": "Re-platforming touches everything; it's too broad for a tool.",
    "reframe": "Its breadth is why parallel agent capacity helps — the same re-platforming pattern applied across many services at once, with humans reviewing, rather than one team grinding service by service.",
    "personaShift": {
      "CFO": "hits cost-driven deadline",
      "CTO": "delivers the platform strategy on time",
      "VPE": "returns senior engineers to high-value work",
      "CRO": "de-risks a stalled, high-stakes migration"
    }
  },
  { "tier": 1, "prompt": "We're translating a huge Perl codebase to Python and it's crawling line by line.", "pattern": "Slow language translation", "rootCause": "Manual, line-by-line translation is the bottleneck.", "consequence": "The migration drags on with no end in sight.", "diagnostic": "At your current pace, when does the Perl-to-Python work actually finish?", "angle": "Agents do the repetitive translation in parallel while engineers own the architecture.", "objection": "Perl has idioms that don't map cleanly to Python.", "reframe": "The non-obvious idioms are where the agent's reasoning earns its place — it translates the intent and verifies behavior, not just the syntax.", "personaShift": { "CTO": "accelerates a stalled translation", "VPE": "frees engineers from line-by-line work", "CFO": "shortens an expensive migration", "CRO": "de-risks a long-running program" } },
  { "tier": 1, "prompt": "We're moving from Oracle to PostgreSQL and the stored-procedure logic is enormous.", "pattern": "Database migration with heavy logic", "rootCause": "Thousands of stored procedures encode business logic that must be ported.", "consequence": "The migration stalls on the sheer volume of procedural code.", "diagnostic": "How many stored procedures are in scope, and who understands what they do?", "angle": "Agents translate the stored-procedure logic and verify behavior against the source.", "objection": "PL/SQL to PL/pgSQL isn't a clean one-to-one mapping.", "reframe": "The dialect differences are well-understood — the agent applies them consistently and tests each procedure's output against the original.", "personaShift": { "CTO": "unsticks a database migration", "VPE": "removes a huge manual porting load", "CFO": "cuts Oracle licensing cost sooner", "CRO": "de-risks a critical data migration" } },
  { "tier": 1, "prompt": "Leadership mandated a move to the cloud but we've barely started after a year.", "pattern": "Stalled cloud mandate", "rootCause": "A cloud directive with no scalable execution path.", "consequence": "A strategic mandate is visibly failing to progress.", "diagnostic": "A year in, what percentage of the estate has actually moved?", "angle": "Agents provide the execution capacity to turn the mandate into steady, measurable progress.", "objection": "Cloud migration needs specialized people we don't have.", "reframe": "The agent supplies the repetitive migration capacity you're missing, so your specialists guide rather than execute every step.", "personaShift": { "CTO": "delivers the cloud mandate credibly", "VPE": "adds execution capacity", "CFO": "converts a stalled mandate to progress", "CRO": "de-risks a high-visibility program" } },
  { "tier": 1, "prompt": "We're rewriting a desktop app as a web app and it's been going for two years.", "pattern": "Long-running rewrite", "rootCause": "A large rewrite with no acceleration is consuming years.", "consequence": "Opportunity cost mounts while the rewrite drags.", "diagnostic": "How much of that two years has been repetitive porting versus genuinely new design?", "angle": "Agents take the repetitive porting so the team focuses on the genuinely new web design.", "objection": "A rewrite is inherently slow; there's no shortcut.", "reframe": "The design isn't the slow part — the repetitive re-implementation is. Agents compress that, so the rewrite finally moves.", "personaShift": { "CTO": "accelerates a stalled rewrite", "VPE": "refocuses the team on new design", "CFO": "reduces opportunity cost", "CRO": "de-risks a multi-year effort" } },
  { "tier": 1, "prompt": "We're migrating from SVN to Git but decades of history and hooks complicate everything.", "pattern": "Toolchain platform migration", "rootCause": "Legacy version-control history and automation don't translate cleanly.", "consequence": "The migration keeps hitting edge cases and stalling.", "diagnostic": "What's actually blocking the cutover — the history, the hooks, or the tooling around it?", "angle": "Agents handle the migration edge cases and rebuild the automation on the new platform.", "objection": "Our SVN setup has too much custom tooling to move.", "reframe": "The custom tooling is exactly what the agent inventories and reimplements — the edge cases that stall a manual move are its routine work.", "personaShift": { "CTO": "completes a stalled platform move", "VPE": "rebuilds automation on the new platform", "CFO": "reduces migration effort", "CRO": "de-risks the cutover" } },
  { "tier": 2, "prompt": "Our migration keeps missing edge cases because the source system's behavior is undocumented.", "pattern": "Undocumented-source migration", "rootCause": "You can't faithfully migrate behavior nobody has documented.", "consequence": "The target keeps diverging from the source in subtle ways.", "diagnostic": "How are you currently discovering the edge cases — in testing, or in production?", "angle": "Agents document the source behavior first, then migrate against that verified specification.", "objection": "We can't document the source and migrate at the same time.", "reframe": "The agent does both in sequence — it extracts the real behavior from the source code, then migrates against it, so edge cases are captured up front, not in production.", "personaShift": { "CTO": "migrates against real behavior", "VPE": "eliminates edge-case surprises", "CFO": "reduces cost of post-migration fixes", "CRO": "reduces migration-defect risk" } },
  { "tier": 2, "prompt": "The real blocker isn't the code, it's that our data model has to change completely.", "pattern": "Data-model transformation", "rootCause": "The migration requires reshaping data, not just porting code.", "consequence": "Data transformation risk overshadows the code migration.", "diagnostic": "Have you mapped how every entity in the old model lands in the new one?", "angle": "Agents build and verify the data transformation mappings alongside the code migration.", "objection": "Getting the data transformation wrong could corrupt everything.", "reframe": "That's why the agent generates the mappings with verification — reconciling old and new records to prove the transformation is correct before cutover.", "personaShift": { "CTO": "handles data and code together", "VPE": "de-risks the data transformation", "CFO": "avoids costly data-corruption incidents", "CRO": "protects data integrity through migration" } },
  { "tier": 2, "prompt": "We got 70% through a migration, then the lead left and it's been frozen since.", "pattern": "Migration knowledge loss", "rootCause": "The migration's context lived in one person who's gone.", "consequence": "A mostly-done migration is stuck with no one able to finish it.", "diagnostic": "Does anyone left understand the state and decisions of the migration so far?", "angle": "Agents reconstruct the migration's state and decisions from the code and finish the remaining work.", "objection": "Nobody left understands where the migration stands.", "reframe": "The agent reconstructs the current state from the code itself — the half-finished work is a map it can read to complete the remaining 30%.", "personaShift": { "CTO": "unfreezes a stalled migration", "VPE": "recovers lost migration context", "CFO": "salvages a large sunk investment", "CRO": "reduces key-person migration risk" } },
  { "tier": 2, "prompt": "Our migration is stalled because testing each converted module by hand is impossibly slow.", "pattern": "Verification bottleneck", "rootCause": "Manual verification can't keep pace with conversion.", "consequence": "Converted code piles up unverified; confidence stays low.", "diagnostic": "How long does it take to validate one converted module by hand today?", "angle": "Agents generate tests and verify converted modules automatically, removing the bottleneck.", "objection": "We can't trust converted code without thorough testing.", "reframe": "Agreed — which is why the agent writes and runs the verification as part of conversion, so each module arrives already validated rather than waiting in a manual queue.", "personaShift": { "CTO": "removes the verification bottleneck", "VPE": "keeps conversion and validation in step", "CFO": "reduces cost of stalled throughput", "CRO": "raises confidence in converted code" } },
  { "tier": 3, "prompt": "Our best engineers have been stuck on this migration for a year and morale is cratering.", "pattern": "Talent burnout on migration", "rootCause": "Senior engineers trapped in repetitive migration grind.", "consequence": "Morale and retention risk among your most valuable people.", "diagnostic": "What would your senior engineers rather be building if they weren't porting code?", "angle": "Agents take the repetitive porting so your seniors return to work that keeps them engaged.", "objection": "The migration needs their expertise; we can't pull them off.", "reframe": "It needs their expertise for the hard decisions — the agent takes the repetitive porting, so their expertise directs the work instead of being consumed by it.", "personaShift": { "VPE": "restores morale and retention", "CTO": "redeploys seniors to high-value work", "CFO": "reduces attrition and rehire cost", "CRO": "reduces key-person flight risk" } },
  { "tier": 3, "prompt": "We're migrating 60 microservices and each one is being done from scratch by hand.", "pattern": "Repetitive per-service migration", "rootCause": "Similar services are being migrated individually with no leverage.", "consequence": "Enormous duplicated effort across near-identical work.", "diagnostic": "How similar are these services really — could one migration pattern cover most of them?", "angle": "Agents apply a consistent migration pattern across all services in parallel — the Itaú consolidation model.", "objection": "Each service is different enough to need individual attention.", "reframe": "Different in detail, similar in shape — the agent handles per-service variation while reusing the common pattern, which is what makes 60 tractable instead of 60 separate projects.", "personaShift": { "CTO": "applies leverage across the estate", "VPE": "eliminates duplicated migration effort", "CFO": "collapses 60 projects into one program", "CRO": "de-risks a large parallel migration" } },
  { "tier": 3, "prompt": "We need to migrate off a vendor platform before our contract renews at a huge price hike.", "pattern": "Cost-driven vendor exit", "rootCause": "A looming renewal makes staying financially painful.", "consequence": "Either eat a large price increase or migrate under time pressure.", "diagnostic": "What's the renewal number, and how does it compare to the cost of migrating off in time?", "angle": "Agents accelerate the vendor exit to beat the renewal deadline and escape the price hike.", "objection": "We can't migrate off that platform before the renewal date.", "reframe": "With agent capacity working the migration in parallel, the timeline that looks impossible manually becomes achievable — turning the renewal from a trap into a deadline you can beat.", "personaShift": { "CFO": "avoids a major price increase", "CTO": "delivers the exit on a hard deadline", "VPE": "supplies the capacity to hit it", "CRO": "reduces vendor lock-in risk" } },
  { "tier": 3, "prompt": "Every migration estimate we get is a range so wide it's useless for planning.", "pattern": "Unestimable migration", "rootCause": "Poor understanding of the source makes estimates wild guesses.", "consequence": "Leadership can't plan or fund with confidence.", "diagnostic": "What's driving the estimate uncertainty — scope, complexity, or not understanding the source?", "angle": "Agents analyze the source to produce a grounded scope, tightening the estimate.", "objection": "You can't estimate a migration like this accurately.", "reframe": "You can once the source is understood — the agent's analysis converts unknowns into a concrete inventory, which is what turns a useless range into a plannable number.", "personaShift": { "CTO": "grounds the migration in real scope", "VPE": "enables confident planning", "CFO": "makes the spend forecastable", "CRO": "reduces planning risk" } },
  { "tier": 2, "prompt": "We're moving to microservices but nobody can agree where the old monolith should be split.", "pattern": "Monolith decomposition uncertainty", "rootCause": "The monolith's internal boundaries are unclear, so splitting it is guesswork.", "consequence": "Decomposition stalls in architectural debate.", "diagnostic": "Do you actually know the real dependency boundaries inside the monolith?", "angle": "Agents map the monolith's true dependencies to reveal natural service boundaries.", "objection": "Where to split is a judgment call no tool can make.", "reframe": "The judgment is yours — the agent gives you the dependency map to base it on, so the debate is informed by the real structure instead of opinions.", "personaShift": { "CTO": "reveals natural service boundaries", "VPE": "unblocks a stalled decomposition", "CFO": "reduces cost of architectural churn", "CRO": "de-risks the split" } },
  { "tier": 4, "prompt": "Our last migration vendor delivered something that technically ran but was full of subtle bugs.", "pattern": "Quality-deficit trust gap", "rootCause": "A prior migration prioritized completion over correctness.", "consequence": "Deep skepticism about migrated-code quality.", "diagnostic": "How did those subtle bugs get through — was there any behavioral verification at all?", "angle": "Agents verify migrated behavior against the source at each step, so correctness isn't an afterthought.", "objection": "How do we know your migration won't have the same subtle bugs?", "reframe": "Because verification is built into every step — the agent compares migrated behavior to the source and surfaces discrepancies, rather than declaring 'it runs' and moving on.", "personaShift": { "CRO": "behavioral verification at each step", "CTO": "correctness by construction", "CFO": "avoids costly post-migration defects", "VPE": "reduces rework from subtle bugs" } },
  { "tier": 4, "prompt": "Our team believes a migration this complex simply can't be trusted to automation.", "pattern": "Complexity-trust objection", "rootCause": "Belief that complexity rules out any automated approach.", "consequence": "The team defaults to slow, fully-manual migration.", "diagnostic": "Which parts of the migration are genuinely novel versus repetitive and mechanical?", "angle": "The agent takes the repetitive majority under human review; humans keep the genuinely novel decisions.", "objection": "A migration this complex can't be automated.", "reframe": "The complexity concentrates in a minority of decisions your team keeps. The repetitive majority — where manual effort actually goes — is what the agent handles, under your review.", "personaShift": { "CTO": "splits novel from mechanical work", "VPE": "keeps humans on the hard decisions", "CFO": "reduces cost of all-manual migration", "CRO": "keeps human oversight where it matters" } },
  { "tier": 4, "prompt": "Leadership says we should just freeze the old system rather than risk migrating it.", "pattern": "Freeze-instead-of-migrate stance", "rootCause": "Migration risk feels larger than the risk of staying put.", "consequence": "The system ossifies and the eventual forced migration is worse.", "diagnostic": "How long can you realistically freeze it before something forces a move anyway?", "angle": "An incremental, verified migration is lower-risk than freezing until a crisis forces a rushed one.", "objection": "Freezing it is safer than risking a migration.", "reframe": "Freezing defers the risk and grows it — the eventual forced migration is rushed and riskier. An incremental, verified move now is the safer path than a crisis move later.", "personaShift": { "CTO": "avoids a future forced-crisis migration", "CFO": "trades a rushed move for a managed one", "VPE": "avoids emergency migration later", "CRO": "reduces the risk of deferral" } },
  { "tier": 3, "prompt": "We're migrating to a new platform but have to keep the old one running in parallel indefinitely.", "pattern": "Prolonged parallel-run cost", "rootCause": "Slow migration forces running two systems at once for too long.", "consequence": "Doubled operational cost and complexity during the overlap.", "diagnostic": "What's it costing to run both systems in parallel every month the migration drags?", "angle": "Agents shorten the migration so the expensive parallel-run window closes sooner.", "objection": "The parallel run is unavoidable during migration.", "reframe": "A short parallel run is fine — the problem is a long one. Agents compress the migration timeline, which directly shrinks the costly overlap.", "personaShift": { "CFO": "shrinks the doubled-cost window", "CTO": "shortens the migration timeline", "VPE": "reduces the burden of running two systems", "CRO": "reduces risk of prolonged dual operation" } },
  { "tier": 2, "prompt": "Our migration keeps regressing because we have no way to compare old and new outputs.", "pattern": "No equivalence checking", "rootCause": "No mechanism to confirm the new system behaves like the old.", "consequence": "Regressions slip through and erode confidence.", "diagnostic": "How do you currently prove the new system matches the old one's outputs?", "angle": "Agents build equivalence checks that compare old and new outputs to catch regressions automatically.", "objection": "Building equivalence tests is a whole project on its own.", "reframe": "The agent generates the equivalence harness as part of the migration — the comparison capability comes with the work rather than being a separate project.", "personaShift": { "CTO": "proves behavioral equivalence", "VPE": "catches regressions automatically", "CFO": "reduces cost of undetected regressions", "CRO": "raises confidence in the migration" } },
  { "tier": 1, "prompt": "We're moving from a proprietary 4GL to a modern language and almost no one knows the old one.", "pattern": "Obscure-source-language migration", "rootCause": "The source is a niche language with vanishing expertise.", "consequence": "Understanding the source is itself a bottleneck.", "diagnostic": "How many people can still read the 4GL you're migrating from?", "angle": "Agents read the obscure source language and translate it, even where human expertise is nearly gone.", "objection": "Almost nobody understands the source language anymore.", "reframe": "That scarcity is exactly why an agent helps — it reads the niche source and produces both documentation and a modern translation your current team can maintain.", "personaShift": { "CTO": "overcomes source-language scarcity", "VPE": "reduces dependence on rare skills", "CFO": "cuts reliance on scarce experts", "CRO": "mitigates knowledge-loss risk" } },
  { "tier": 3, "prompt": "Our migration has no clear finish line — it just keeps expanding as we discover more.", "pattern": "Scope-creep migration", "rootCause": "Undiscovered scope keeps expanding the migration mid-flight.", "consequence": "The program feels endless and unbudgetable.", "diagnostic": "Is the scope genuinely growing, or are you just discovering scope that was always there?", "angle": "Agents inventory the full scope up front so the finish line is defined, not discovered.", "objection": "We keep finding more to migrate; there's no defining the scope.", "reframe": "You're discovering pre-existing scope, not creating it — the agent surfaces the whole inventory early, so the finish line is set at the start instead of receding.", "personaShift": { "CTO": "defines the true scope up front", "VPE": "gives the migration a real finish line", "CFO": "makes the program budgetable", "CRO": "reduces open-ended program risk" } },
  { "tier": 2, "prompt": "We're consolidating three acquired companies' systems that all do the same thing differently.", "pattern": "Post-acquisition consolidation", "rootCause": "Redundant systems from acquisitions must be unified.", "consequence": "Triple the maintenance for one capability until consolidated.", "diagnostic": "How much are you spending maintaining three systems that serve one purpose?", "angle": "Agents analyze all three, map the overlaps, and drive consolidation onto one target.", "objection": "Each acquired system has its own logic we can't just merge.", "reframe": "The agent reconciles the three by mapping each system's logic to a common target and verifying behavior — the reconciliation that's daunting manually is its core strength.", "personaShift": { "CFO": "collapses triple maintenance cost", "CTO": "unifies redundant systems", "VPE": "reduces the systems to maintain", "CRO": "reduces fragmentation risk" } },
  { "tier": 4, "prompt": "Our CFO wants a fixed price for the migration and won't accept 'it depends'.", "pattern": "Fixed-price expectation", "rootCause": "Migration uncertainty clashes with a demand for a fixed number.", "consequence": "Deadlock between finance and engineering on how to commit.", "diagnostic": "Would a fixed-price, fixed-scope first slice give finance the certainty it needs to proceed?", "angle": "Prove one bounded slice at a fixed price to calibrate the rest, replacing 'it depends' with data.", "objection": "We need a fixed price for the whole migration up front.", "reframe": "A fixed price on the unknown whole is a gamble for both sides. A fixed-price first slice gives real throughput data, so the rest can be priced from evidence, not guesses.", "personaShift": { "CFO": "gets fixed-price certainty on a slice", "CTO": "calibrates the program with real data", "VPE": "avoids over-committing on unknowns", "CRO": "reduces commercial risk" } },
  { "tier": 3, "prompt": "We're migrating our data warehouse and the ETL logic is thousands of undocumented jobs.", "pattern": "ETL migration at scale", "rootCause": "Vast, undocumented data-pipeline logic must be ported.", "consequence": "Analytics migration stalls on opaque pipeline volume.", "diagnostic": "Could anyone tell you what all those ETL jobs actually produce today?", "angle": "Agents document and translate the ETL logic to the new platform at scale.", "objection": "There are too many ETL jobs to migrate reliably.", "reframe": "Volume plus repetition is where agents excel — they translate the jobs in parallel and verify outputs against the source, which manual porting can't match.", "personaShift": { "CTO": "migrates analytics reliably at scale", "VPE": "removes an opaque pipeline blocker", "CFO": "moves analytics to cheaper platforms", "CRO": "preserves data-pipeline integrity" } },
  { "tier": 1, "prompt": "We're porting a legacy Fortran scientific codebase to a modern language.", "pattern": "Scientific-code migration", "rootCause": "Decades-old Fortran encodes numerical logic that must be preserved exactly.", "consequence": "Any translation error could silently corrupt results.", "diagnostic": "How would you know if the migrated code produced subtly different numbers?", "angle": "Agents translate the numerical logic and verify results match the original to precision.", "objection": "Numerical code is too sensitive to risk translating.", "reframe": "Sensitivity is why verification matters — the agent checks migrated outputs against the original within tolerance, so precision is proven, not assumed.", "personaShift": { "CTO": "modernizes without losing precision", "VPE": "de-risks numerical translation", "CFO": "extends the life of valuable models", "CRO": "protects result integrity" } },
  { "tier": 2, "prompt": "The migration is blocked because the old and new systems have to stay in sync during cutover.", "pattern": "Sync-during-cutover challenge", "rootCause": "Live data must stay consistent across both systems through the transition.", "consequence": "Cutover risk keeps pushing the go-live date.", "diagnostic": "What's your plan to keep both systems consistent during the switchover window?", "angle": "Agents build and verify the synchronization and reconciliation logic that de-risks cutover.", "objection": "Keeping both systems in sync during cutover is the scariest part.", "reframe": "Which is why the agent builds the sync and reconciliation checks explicitly and tests them before go-live — turning the scariest part into a verified procedure.", "personaShift": { "CTO": "de-risks the cutover", "VPE": "makes go-live a controlled event", "CFO": "avoids a costly failed cutover", "CRO": "protects data consistency through transition" } },
  { "tier": 3, "prompt": "We keep restarting the migration with new leadership and never finish under one plan.", "pattern": "Leadership-churn derailment", "rootCause": "Each leadership change resets the migration approach.", "consequence": "Sunk cost accumulates with no completion.", "diagnostic": "How many times has the migration approach been reset, and what has that cost?", "angle": "Agents deliver visible, incremental progress that survives leadership changes by producing durable results early.", "objection": "Every new leader wants to start over their way.", "reframe": "Continuous, verifiable delivery makes restarts less tempting — when each increment ships working results, new leadership inherits momentum worth keeping rather than a stalled plan to replace.", "personaShift": { "CTO": "builds restart-resistant momentum", "VPE": "delivers durable incremental results", "CFO": "protects accumulated investment", "CRO": "reduces program-continuity risk" } },
  { "tier": 4, "prompt": "Our engineers argue that if they don't do the migration by hand, they'll lose understanding of the system.", "pattern": "Understanding-through-toil belief", "rootCause": "Belief that manual porting is the only way to retain system knowledge.", "consequence": "The team insists on slow manual work to preserve understanding.", "diagnostic": "Does understanding come from typing the port, or from reviewing and directing it?", "angle": "Agents generate documentation and reviewable changes, so the team gains understanding through review rather than repetitive typing.", "objection": "If we automate it, we'll lose our grasp of the system.", "reframe": "Understanding comes from engaging with the logic — which happens in reviewing the agent's documented changes, not in the mechanical typing. The team stays close to the system without the grind.", "personaShift": { "VPE": "preserves understanding via review", "CTO": "retains knowledge without the toil", "CFO": "gets understanding and speed", "CRO": "documents the system as a byproduct" } },
  { "tier": 2, "prompt": "Our migration target keeps changing because the new platform is still being designed.", "pattern": "Unstable-target migration", "rootCause": "Migrating toward a platform whose design isn't settled.", "consequence": "Rework as the target shifts underneath the migration.", "diagnostic": "How settled is the new platform's design, really, before you migrate onto it?", "angle": "Agents adapt migrated code quickly as the target stabilizes, absorbing the churn.", "objection": "We can't migrate to a platform that's still changing.", "reframe": "You can if adapting to target changes is cheap — the agent re-applies migrated work against the evolving target, so churn becomes manageable rather than blocking.", "personaShift": { "CTO": "migrates alongside an evolving target", "VPE": "absorbs target churn cheaply", "CFO": "reduces rework cost", "CRO": "reduces risk of an unstable target" } },
  { "tier": 3, "prompt": "We need to migrate but can't afford any downtime on a 24/7 system.", "pattern": "Zero-downtime migration", "rootCause": "A continuously-operating system leaves no maintenance window.", "consequence": "Standard migration approaches that need downtime are off the table.", "diagnostic": "What's the cost of even an hour of downtime on that system?", "angle": "Agents help design and verify an incremental, zero-downtime migration path.", "objection": "There's no window to cut over without downtime.", "reframe": "That's why it's done incrementally with parallel-run and verified switchover per component — the agent supports a phased path that never requires a full-system outage.", "personaShift": { "CTO": "enables a zero-downtime path", "VPE": "phases cutover safely", "CFO": "avoids downtime revenue loss", "CRO": "protects continuous operations" } },
  { "tier": 1, "prompt": "We're moving on-prem apps to containers but they were never built to run that way.", "pattern": "Containerization migration", "rootCause": "Legacy apps assume a traditional environment, not containers.", "consequence": "Each app needs rework to run in the new model.", "diagnostic": "How many of your apps make assumptions that won't hold in a container?", "angle": "Agents identify and fix the assumptions that block containerization across the app estate.", "objection": "Our apps weren't designed for containers at all.", "reframe": "The agent finds each container-hostile assumption — local state, hard-coded paths, config — and fixes them systematically, which is what makes non-cloud-native apps movable.", "personaShift": { "CTO": "enables containerization at scale", "VPE": "removes per-app rework burden", "CFO": "accelerates the cloud move", "CRO": "de-risks the platform shift" } }
];
