export default [
  {
    "tier": 3,
    "prompt": "Only Dave really understands the payments service, and Dave's going on sabbatical.",
    "pattern": "Key-person / tribal knowledge",
    "rootCause": "No documentation, no tests, an opaque system only one person understands.",
    "consequence": "Every change is high-risk; onboarding takes months; acute bus-factor risk.",
    "diagnostic": "What's your bus factor on that service — and what's your plan when it goes to one?",
    "angle": "Agents generate the documentation and test coverage that was never written, turning an opaque system legible.",
    "objection": "Dave's knowledge is too nuanced to document automatically.",
    "reframe": "It won't replace Dave's intuition — it captures the mechanical reality of the code so the next engineer inherits a map instead of a mystery. Dave reviews it once and it's durable.",
    "personaShift": {
      "CRO": "removes single-point-of-failure risk",
      "VPE": "onboarding drops from months to weeks",
      "CTO": "de-risks a critical service",
      "CFO": "reduces cost of slow ramp and rework"
    }
  },
  {
    "tier": 2,
    "prompt": "We have no tests on our oldest services, so we change them as little as possible.",
    "pattern": "Test-coverage vacuum",
    "rootCause": "Tests were never written; fear of change has calcified the system.",
    "consequence": "Frozen code, slow delivery, mounting hidden risk.",
    "diagnostic": "Which service would you change more freely if you actually trusted a test suite around it?",
    "angle": "Agents write the missing safety net as they modernize — coverage typically rises substantially, unlocking safe change.",
    "objection": "Writing tests for that old code would take forever.",
    "reframe": "For a human, yes — which is why it never happened. The agent writes the coverage as part of the work, so you get the safety net without pulling engineers off delivery.",
    "personaShift": {
      "VPE": "unfreezes delivery on legacy code",
      "CTO": "converts fragile systems into changeable ones",
      "CFO": "reduces cost of slow ramp and rework",
      "CRO": "removes single-point-of-failure risk"
    }
  },
  {
    "tier": 1,
    "prompt": "When someone leaves, it takes new hires three months just to understand our codebase.",
    "pattern": "Onboarding drag from opacity",
    "rootCause": "Undocumented, inconsistent code that's hard to ramp into.",
    "consequence": "Slow time-to-productivity; expensive ramp; retention pressure.",
    "diagnostic": "What does it cost you to have a new senior hire non-productive for a full quarter?",
    "angle": "Agent-generated documentation and consistent patterns compress ramp time.",
    "objection": "Onboarding is just hard; that's normal.",
    "reframe": "Some of it is inherent — but a lot of the three months is deciphering undocumented code. Remove that and you're onboarding into a legible system, not an archaeology dig.",
    "personaShift": {
      "CFO": "reduces cost of non-productive ramp",
      "VPE": "faster team scaling",
      "CTO": "turns opaque systems legible and changeable",
      "CRO": "removes single-point-of-failure risk"
    }
  },
  {
    "tier": 2,
    "prompt": "Our documentation is either missing or so out of date it's worse than nothing.",
    "pattern": "Documentation rot",
    "rootCause": "Docs were never maintained; they now actively mislead.",
    "consequence": "Engineers distrust docs, slowing everyone and raising error risk.",
    "diagnostic": "Do your engineers trust the docs, or do they just read the code because the docs lie?",
    "angle": "Agents generate documentation from the actual current code, so it reflects reality and stays maintainable.",
    "objection": "Auto-generated docs are always shallow and useless.",
    "reframe": "Shallow docs describe what; good agent-generated docs capture how and why from the real code. And because they're generated from source, they can be regenerated as the code evolves rather than rotting again.",
    "personaShift": {
      "VPE": "trustworthy docs speed delivery",
      "CTO": "durable, maintainable knowledge base",
      "CFO": "reduces cost of slow ramp and rework",
      "CRO": "removes single-point-of-failure risk"
    }
  },
  {
    "tier": 3,
    "prompt": "We're scared to refactor anything because we don't know what depends on what.",
    "pattern": "Dependency-opacity paralysis",
    "rootCause": "Hidden, undocumented dependencies make every change feel dangerous.",
    "consequence": "Change paralysis; the codebase calcifies and slows everything.",
    "diagnostic": "When you consider changing something, how do you currently figure out what it might break?",
    "angle": "Agents trace and map dependencies so refactoring becomes informed and safe rather than a gamble.",
    "objection": "Our dependencies are too implicit for anything to trace reliably.",
    "reframe": "Implicit dependencies are precisely what methodical tracing surfaces — the agent follows the actual call paths and data flows, giving you the map that lets you refactor with confidence.",
    "personaShift": {
      "CTO": "restores safe changeability",
      "VPE": "unfreezes refactoring",
      "CRO": "reduces unintended-breakage risk",
      "CFO": "reduces cost of slow ramp and rework"
    }
  },
  { "tier": 1, "prompt": "Our deployment process lives entirely in one engineer's head and a set of personal scripts.", "pattern": "Undocumented deployment knowledge", "rootCause": "Release process exists only as one person's tacit routine.", "consequence": "Nobody else can safely ship if that person is out.", "diagnostic": "If that engineer were unreachable during an outage, could anyone deploy a fix?", "angle": "Agents document the deploy process and scripts into a runbook anyone can follow.", "objection": "The process has too many undocumented steps to capture.", "reframe": "The agent traces the actual scripts and commands to reconstruct the real process — the undocumented steps are exactly what it surfaces into a runbook.", "personaShift": { "CRO": "removes single-person deploy risk", "VPE": "lets anyone ship safely", "CTO": "de-risks releases", "CFO": "reduces cost of deploy bottlenecks" } },
  { "tier": 1, "prompt": "When our lead architect retires next year, a huge amount of context leaves with her.", "pattern": "Impending expert departure", "rootCause": "Critical architectural context lives only in one person about to leave.", "consequence": "A known cliff-edge of knowledge loss is approaching.", "diagnostic": "What does your architect know that isn't written down anywhere?", "angle": "Agents capture the architectural knowledge from the code before the departure date.", "objection": "Her knowledge is too high-level to extract from code.", "reframe": "Some is judgment, but much is embedded in the systems she designed — the agent documents that structure now, so what remains after she leaves is a map, not a mystery.", "personaShift": { "CRO": "beats a known knowledge-loss deadline", "CTO": "preserves architectural context", "VPE": "eases the succession", "CFO": "reduces cost of lost expertise" } },
  { "tier": 1, "prompt": "Nobody knows why half our config flags exist or what turning them off would do.", "pattern": "Mystery configuration", "rootCause": "Config accreted over years with no record of purpose.", "consequence": "Changes are avoided out of fear; cruft accumulates.", "diagnostic": "How many config flags could you confidently remove today without worry?", "angle": "Agents trace where each flag is used and document its real effect.", "objection": "Some of those flags might do something critical we've forgotten.", "reframe": "That's the point of tracing them — the agent finds every place each flag is read and documents its actual behavior, so you decide from facts, not fear.", "personaShift": { "CTO": "makes configuration legible", "VPE": "enables safe cleanup", "CRO": "reduces risk of unknown settings", "CFO": "reduces maintenance overhead" } },
  { "tier": 2, "prompt": "Our system works but nobody actually understands why some of the trickiest parts work.", "pattern": "Cargo-cult code", "rootCause": "Code was kept because it works, not because anyone understands it.", "consequence": "Changes near it are terrifying and error-prone.", "diagnostic": "Which parts of the system does your team change only by copying what's already there?", "angle": "Agents analyze and explain the tricky code so it can be changed with understanding.", "objection": "If it works, why risk understanding it and breaking something?", "reframe": "Because 'we don't know why it works' means you also don't know when it'll stop. The agent documents the why, turning fragile luck into understood, changeable code.", "personaShift": { "CTO": "replaces luck with understanding", "VPE": "makes scary code approachable", "CRO": "reduces risk of not-understood code", "CFO": "reduces cost of fearful changes" } },
  { "tier": 2, "prompt": "Our runbooks are years out of date so people just ask the one person who knows.", "pattern": "Stale operational knowledge", "rootCause": "Documentation decayed, so tribal knowledge became the real source.", "consequence": "Operations funnel through a human bottleneck.", "diagnostic": "How often does an incident stall because the only up-to-date knowledge is in someone's head?", "angle": "Agents regenerate current runbooks from the actual system so docs stop decaying.", "objection": "Docs always go stale; there's no point refreshing them.", "reframe": "Manual docs decay — but the agent can regenerate them from the live system, so they stay current instead of drifting into uselessness.", "personaShift": { "VPE": "removes the human knowledge bottleneck", "CTO": "keeps operational docs current", "CRO": "reduces single-person operational risk", "CFO": "reduces cost of stalled incidents" } },
  { "tier": 2, "prompt": "The reason changes are slow is that only one team truly understands the shared platform.", "pattern": "Platform-knowledge monopoly", "rootCause": "Understanding of the shared platform is concentrated in one team.", "consequence": "Every other team is bottlenecked on that team's availability.", "diagnostic": "How many other teams are blocked waiting on the platform team's knowledge?", "angle": "Agents document the platform so consuming teams can self-serve safely.", "objection": "The platform is too complex for other teams to understand.", "reframe": "Complexity is why it needs documenting, not gatekeeping — the agent produces the guidance that lets other teams work against the platform without waiting on the experts.", "personaShift": { "VPE": "unblocks dependent teams", "CTO": "spreads platform understanding", "CFO": "reduces cost of cross-team bottlenecks", "CRO": "reduces knowledge-concentration risk" } },
  { "tier": 3, "prompt": "We can't estimate work on the old system because nobody knows what's involved until they dig in.", "pattern": "Unestimable legacy work", "rootCause": "Opacity means effort is unknown until someone starts digging.", "consequence": "Planning is guesswork; commitments are unreliable.", "diagnostic": "How far off are your estimates on the old system versus the new one?", "angle": "Agents document the system so work can be scoped before it's started.", "objection": "You can't estimate legacy work reliably; that's just how it is.", "reframe": "It's how it is while the system is opaque — with the agent's documentation of what's actually there, the digging happens up front, so estimates rest on knowledge, not surprises.", "personaShift": { "CTO": "makes legacy work estimable", "VPE": "enables reliable planning", "CFO": "makes spend forecastable", "CRO": "reduces planning risk" } },
  { "tier": 3, "prompt": "Onboarding a new engineer to our core system takes six months of shadowing.", "pattern": "Extreme onboarding drag", "rootCause": "Knowledge transfer depends on shadowing because nothing is written down.", "consequence": "New hires are unproductive for half a year.", "diagnostic": "What would a new hire being productive in weeks instead of months be worth?", "angle": "Agent-generated documentation compresses the shadowing period dramatically.", "objection": "There's no substitute for learning our system hands-on.", "reframe": "Hands-on stays valuable — but much of six months is deciphering undocumented code. Give new hires a real map and the hands-on time teaches judgment, not archaeology.", "personaShift": { "VPE": "cuts onboarding from months to weeks", "CTO": "accelerates team ramp", "CFO": "reduces cost of long unproductive ramp", "CRO": "reduces dependence on shadowing experts" } },
  { "tier": 3, "prompt": "Every incident on our legacy system turns into a scavenger hunt for whoever remembers it.", "pattern": "Incident-response knowledge gaps", "rootCause": "No documented system knowledge to support incident response.", "consequence": "Longer outages while people hunt for context.", "diagnostic": "How much of your mean-time-to-recovery is spent just finding who knows the system?", "angle": "Agents produce the system documentation that shortens incident diagnosis.", "objection": "Incidents are too varied to document ahead of time.", "reframe": "You can't document every incident, but you can document the system — and knowing how it works is most of what the scavenger hunt is trying to reconstruct under pressure.", "personaShift": { "VPE": "shortens incident response", "CTO": "supports faster recovery", "CFO": "reduces cost of prolonged outages", "CRO": "reduces reliance on individual memory" } },
  { "tier": 4, "prompt": "Our expert says documenting the system would take him months he doesn't have.", "pattern": "Documentation-cost objection", "rootCause": "The one person who could document it has no time to.", "consequence": "Documentation never happens; the knowledge stays trapped.", "diagnostic": "What if the documentation could be drafted for him to review instead of write?", "angle": "The agent drafts the documentation from the code; the expert reviews and corrects rather than authors.", "objection": "Our expert doesn't have months to write documentation.", "reframe": "He doesn't have to write it — the agent drafts it from the code and he reviews it. That turns months of authoring into hours of correction.", "personaShift": { "VPE": "documentation without expert authoring time", "CTO": "captures knowledge affordably", "CFO": "avoids months of expert time cost", "CRO": "secures knowledge before it's lost" } },
  { "tier": 4, "prompt": "Our senior engineers quietly like being the only ones who understand the system.", "pattern": "Knowledge as job security", "rootCause": "Experts have an incentive to keep knowledge tacit.", "consequence": "Deliberate opacity blocks documentation efforts.", "diagnostic": "What would make your experts more valuable — being the bottleneck, or leading the work the documentation frees them for?", "angle": "Reframe documentation as elevating experts into leaders and architects, not diminishing them.", "objection": "Our experts won't cooperate with anything that dilutes what makes them essential.", "reframe": "Being a bottleneck caps their impact. Documenting the routine frees them for higher-value work — they stay essential as the people directing it, not the only ones who can do it.", "personaShift": { "VPE": "aligns experts with sharing knowledge", "CTO": "elevates experts to architects", "CFO": "reduces bottleneck cost", "CRO": "reduces deliberate key-person risk" } },
  { "tier": 2, "prompt": "Our data pipeline has hidden assumptions that only surface when something breaks.", "pattern": "Hidden data assumptions", "rootCause": "Implicit assumptions baked into the pipeline are undocumented.", "consequence": "Breakage from assumptions no one knew were there.", "diagnostic": "How many pipeline outages traced back to an assumption nobody had written down?", "angle": "Agents surface and document the implicit assumptions in the pipeline.", "objection": "By definition we don't know what the hidden assumptions are.", "reframe": "The agent finds them by analyzing the code and data flows — surfacing the implicit assumptions is exactly what turns hidden landmines into documented facts.", "personaShift": { "CTO": "makes hidden assumptions explicit", "VPE": "reduces surprise breakage", "CRO": "reduces risk from unknown assumptions", "CFO": "reduces cost of assumption-driven outages" } },
  { "tier": 1, "prompt": "Our most important spreadsheet macro was written by someone who left five years ago.", "pattern": "Orphaned critical artifact", "rootCause": "A business-critical artifact has no living owner or documentation.", "consequence": "Reliance on something nobody can maintain or explain.", "diagnostic": "What happens the day that macro breaks and nobody can fix it?", "angle": "Agents analyze and document the orphaned artifact so it can be maintained or replaced.", "objection": "It's just a spreadsheet macro; it's not worth the effort.", "reframe": "If the business depends on it, its orphan status is a real risk. The agent documents what it does cheaply, so you can maintain or safely replace it before it fails.", "personaShift": { "CTO": "makes an orphaned artifact maintainable", "VPE": "removes an unowned dependency", "CRO": "reduces risk of a critical unknown", "CFO": "avoids a costly surprise failure" } },
  { "tier": 3, "prompt": "We're afraid to refactor because we don't know what business rules are hidden in the code.", "pattern": "Hidden-business-rule risk", "rootCause": "Business rules are embedded in code but not documented anywhere.", "consequence": "Refactoring risks silently dropping a rule the business depends on.", "diagnostic": "If a refactor accidentally removed a business rule, how would you even notice?", "angle": "Agents extract and document the embedded business rules before any refactor.", "objection": "We can't refactor safely without knowing every rule buried in there.", "reframe": "Which is why the agent extracts those rules first — it documents what the code actually enforces, so refactoring preserves the rules deliberately instead of by luck.", "personaShift": { "CTO": "enables safe refactoring", "VPE": "removes fear of hidden rules", "CRO": "protects business rules through change", "CFO": "reduces cost of accidental rule loss" } },
  { "tier": 2, "prompt": "Our test suite has cryptic tests nobody understands, so failures get ignored or skipped.", "pattern": "Opaque test suite", "rootCause": "Tests exist but their intent is undocumented, so failures aren't trusted.", "consequence": "The safety net is ignored, defeating its purpose.", "diagnostic": "When a test fails, does your team investigate or just skip it?", "angle": "Agents document what each test verifies so failures become meaningful again.", "objection": "Those tests are too cryptic to make sense of now.", "reframe": "The agent reads each test and documents what behavior it's protecting — turning cryptic red into actionable signal your team can trust again.", "personaShift": { "VPE": "restores trust in the test suite", "CTO": "makes tests meaningful again", "CRO": "reduces risk of ignored failures", "CFO": "reduces cost of skipped-test defects" } },
  { "tier": 4, "prompt": "Leadership thinks documentation is a nice-to-have we can always do later.", "pattern": "Documentation deprioritized", "rootCause": "Documentation is treated as optional overhead, not risk mitigation.", "consequence": "The knowledge-loss risk grows unaddressed.", "diagnostic": "What's the cost the day a key person leaves with undocumented knowledge?", "angle": "Agents make documentation cheap enough that it stops being a trade-off against delivery.", "objection": "Documentation is always the thing we can put off.", "reframe": "It's put off because it's expensive to do manually. When the agent generates it as a byproduct of the work, it's no longer a trade-off — you get delivery and the risk mitigation.", "personaShift": { "CRO": "closes a growing knowledge-loss risk", "CTO": "documentation without a delivery trade-off", "VPE": "keeps docs current cheaply", "CFO": "avoids the cost of a knowledge cliff" } },
  { "tier": 1, "prompt": "Our integration with a key partner is a black box only one contractor understood.", "pattern": "Opaque integration ownership", "rootCause": "A critical integration's logic left with a departed contractor.", "consequence": "The partner integration can't be safely changed.", "diagnostic": "If that partner changed their API tomorrow, who could update the integration?", "angle": "Agents document the integration logic so it becomes maintainable in-house.", "objection": "The integration is too specialized for our team to take over.", "reframe": "The agent reconstructs how it works from the code and documents it, so your team can own and update it rather than depending on someone who's gone.", "personaShift": { "CTO": "brings a key integration in-house", "VPE": "makes the integration maintainable", "CRO": "reduces dependence on a lost contractor", "CFO": "reduces risk to a partner relationship" } },
  { "tier": 3, "prompt": "We keep re-solving the same problems because nobody knows what's already been built.", "pattern": "Undiscoverable prior work", "rootCause": "No documentation or discoverability of existing solutions.", "consequence": "Wasted effort reinventing things that already exist.", "diagnostic": "How often does someone build something only to find it already existed?", "angle": "Agents document and index existing capabilities so teams reuse instead of rebuild.", "objection": "Our codebase is too big for anyone to know what's in it.", "reframe": "Too big for a person, yes — the agent inventories and documents what exists, making prior work discoverable so teams stop paying to rebuild it.", "personaShift": { "VPE": "reduces duplicated effort", "CTO": "makes existing capabilities discoverable", "CFO": "eliminates reinvention cost", "CRO": "reduces fragmentation risk" } },
  { "tier": 2, "prompt": "Our system's error messages are internal codes only long-timers can decode.", "pattern": "Undocumented error semantics", "rootCause": "Error codes have meaning only in veterans' memories.", "consequence": "New staff can't diagnose issues without an expert.", "diagnostic": "Could a new engineer resolve a production error code without asking a veteran?", "angle": "Agents document the error codes and their causes into a usable reference.", "objection": "The error codes are too idiosyncratic to document.", "reframe": "The agent traces where each code is raised and why, producing the reference that turns veteran memory into a document anyone can use.", "personaShift": { "VPE": "empowers new staff to diagnose", "CTO": "makes errors self-explanatory", "CRO": "reduces reliance on veteran memory", "CFO": "reduces cost of diagnosis delays" } },
  { "tier": 4, "prompt": "Our team worries that AI-written documentation will be subtly wrong and mislead people.", "pattern": "Documentation-accuracy concern", "rootCause": "Fear that generated docs will contain confident errors.", "consequence": "Hesitation to trust or adopt generated documentation.", "diagnostic": "Would documentation your engineers review and approve be more trustworthy than the nothing you have now?", "angle": "Generated docs are a reviewed draft — your engineers verify them, so they're more accurate than tribal memory and safer than no docs.", "objection": "AI documentation could be subtly wrong and mislead the team.", "reframe": "It's a draft your engineers review before it's trusted — grounded in the actual code, then human-verified. That's more reliable than undocumented memory, not less.", "personaShift": { "CTO": "reviewed, code-grounded documentation", "VPE": "trustworthy docs via human review", "CRO": "reduces reliance on unverifiable memory", "CFO": "avoids the cost of no documentation" } },
  { "tier": 3, "prompt": "Our compliance team can't verify controls because nobody can explain how the system enforces them.", "pattern": "Unverifiable controls", "rootCause": "Control logic is embedded in code no one can explain to auditors.", "consequence": "Compliance evidence is weak and manually reconstructed.", "diagnostic": "Could you show an auditor exactly where and how each control is enforced in code?", "angle": "Agents document where and how controls are implemented, producing durable compliance evidence.", "objection": "Explaining control implementation to auditors is always a manual scramble.", "reframe": "The agent traces each control to its enforcement point in the code and documents it — turning the annual scramble into standing, reviewable evidence.", "personaShift": { "CRO": "produces verifiable control evidence", "CTO": "makes control logic explainable", "VPE": "ends the audit scramble", "CFO": "reduces audit-preparation cost" } },
  { "tier": 1, "prompt": "Half of what keeps our system running is undocumented cron jobs on random servers.", "pattern": "Hidden operational glue", "rootCause": "Critical automation scattered as undocumented scheduled jobs.", "consequence": "Invisible dependencies that fail silently and mysteriously.", "diagnostic": "Do you have a complete inventory of every scheduled job keeping things running?", "angle": "Agents discover and document the scattered jobs into a single operational map.", "objection": "Those jobs are spread across too many places to find them all.", "reframe": "Finding scattered automation is exactly what an agent does well — it inventories the jobs across your servers and documents what each one does and depends on.", "personaShift": { "CTO": "maps hidden operational glue", "VPE": "eliminates invisible dependencies", "CRO": "reduces silent-failure risk", "CFO": "reduces cost of mysterious outages" } },
  { "tier": 2, "prompt": "We inherited a system in a reorg and the team that built it is now scattered across the company.", "pattern": "Dispersed ownership", "rootCause": "The building team dispersed, fragmenting the system knowledge.", "consequence": "No coherent owner or understanding remains.", "diagnostic": "Is there anyone who can describe the whole system now, or only pieces of it?", "angle": "Agents reconstruct a coherent, whole-system understanding from the code.", "objection": "The knowledge is scattered across people who've all moved on.", "reframe": "The code is the one place the whole system still lives together — the agent reads it to rebuild the unified understanding the dispersed team no longer holds.", "personaShift": { "CTO": "reconstructs whole-system understanding", "VPE": "restores a coherent picture", "CRO": "reduces dispersed-knowledge risk", "CFO": "reduces cost of fragmented ownership" } },
  { "tier": 3, "prompt": "Our biggest delivery risk is that too much depends on two or three irreplaceable people.", "pattern": "Concentrated bus-factor risk", "rootCause": "Critical delivery capacity concentrated in a few individuals.", "consequence": "Any of them leaving would severely disrupt delivery.", "diagnostic": "What's your bus factor on your most critical systems — and are you comfortable with it?", "angle": "Agents document the systems those people hold, spreading the knowledge and reducing the risk.", "objection": "You can't replace what those people know; it's irreplaceable.", "reframe": "You don't replace them — you reduce the dependency. The agent documents what they hold, so a departure is a setback, not a catastrophe.", "personaShift": { "CRO": "reduces concentrated bus-factor risk", "CTO": "spreads critical knowledge", "VPE": "de-risks delivery capacity", "CFO": "reduces cost of key-person disruption" } },
  { "tier": 2, "prompt": "Nobody documented our API's undocumented behaviors that clients now secretly depend on.", "pattern": "Accidental API contract", "rootCause": "Clients rely on unintended behaviors that were never specified.", "consequence": "Any change risks breaking clients in unknown ways.", "diagnostic": "Do you know which of your API's quirks clients have come to depend on?", "angle": "Agents analyze usage and document the de facto contract, including the accidental behaviors.", "objection": "We can't know which quirks clients rely on.", "reframe": "The agent analyzes actual usage patterns and the API code to surface the de facto contract, so you change with awareness of what clients truly depend on.", "personaShift": { "CTO": "documents the real API contract", "VPE": "enables safe API evolution", "CRO": "reduces client-breakage risk", "CFO": "protects client relationships" } },
  { "tier": 4, "prompt": "Our engineers say the system is too unique for any tool to understand it.", "pattern": "Uniqueness objection", "rootCause": "Belief that the system's idiosyncrasy defeats any analysis.", "consequence": "Documentation efforts are dismissed before they start.", "diagnostic": "What would convince your team — a documentation sample on a module they know cold?", "angle": "Prove it on a module the team knows well and let them judge the generated documentation's accuracy.", "objection": "Our system is too unique for a tool to understand.", "reframe": "Every system feels unique — so don't take my word for it. Point it at a module your team knows cold and judge the documentation. The experts become the verifiers.", "personaShift": { "CTO": "converts skeptics through proof", "VPE": "wins buy-in via demonstration", "CRO": "reduces knowledge risk once proven", "CFO": "avoids cost of dismissed efforts" } },
  { "tier": 1, "prompt": "Our permissions and access rules are a tangle nobody can fully explain anymore.", "pattern": "Opaque authorization logic", "rootCause": "Access rules accreted with no coherent documentation.", "consequence": "Security and correctness of access can't be reasoned about.", "diagnostic": "Could anyone tell you exactly who can access what and why today?", "angle": "Agents map and document the authorization logic so access can be reasoned about and audited.", "objection": "The permission logic is too tangled to untangle safely.", "reframe": "The agent traces the rules across the code to produce the access map no one holds — untangling exactly the kind of sprawl that's dangerous to leave opaque.", "personaShift": { "CRO": "makes access auditable", "CTO": "makes authorization reasonable-about", "VPE": "enables safe access changes", "CFO": "reduces risk of access errors" } },
  { "tier": 3, "prompt": "We can't modernize because we can't tell which parts of the system are even still used.", "pattern": "Unknown usage footprint", "rootCause": "No visibility into which components are live versus dormant.", "consequence": "Modernization can't prioritize without knowing what matters.", "diagnostic": "What fraction of your system do you think is actually exercised in production?", "angle": "Agents analyze usage to document what's live, dormant, or dead, focusing modernization effort.", "objection": "We have no way to tell what's still in use.", "reframe": "The agent combines code analysis and usage signals to map what's actually exercised — giving you the live/dead picture that lets modernization target what matters.", "personaShift": { "CTO": "focuses modernization on live code", "VPE": "avoids wasted effort on dead code", "CFO": "directs spend to what matters", "CRO": "reduces risk of touching the wrong things" } },
  { "tier": 2, "prompt": "Our disaster-recovery plan assumes knowledge that only exists in a few people's heads.", "pattern": "Undocumented recovery knowledge", "rootCause": "DR depends on tacit expertise, not a followable plan.", "consequence": "Recovery could fail if those people are unavailable in a real disaster.", "diagnostic": "In a real disaster with your experts unreachable, could the team actually recover?", "angle": "Agents document the system knowledge the DR plan implicitly assumes, making recovery executable by anyone.", "objection": "Real recovery always depends on people who know the system.", "reframe": "That dependence is the risk — the agent documents the system knowledge the plan assumes, so recovery follows a runbook rather than hoping the right person answers the phone.", "personaShift": { "CRO": "makes recovery executable without key people", "CTO": "de-risks disaster recovery", "VPE": "lets any responder execute DR", "CFO": "reduces catastrophic-failure cost" } },
  { "tier": 1, "prompt": "Our billing logic has special cases for specific customers that only sales remembers.", "pattern": "Tribal business exceptions", "rootCause": "Customer-specific rules live in memory, not documentation.", "consequence": "Billing errors when the wrong person is asked or forgets.", "diagnostic": "How many customer-specific billing rules exist only in someone's memory?", "angle": "Agents surface the special-case logic from the code and document each exception.", "objection": "Those exceptions are business decisions, not code we can just document.", "reframe": "Wherever they're enforced, they live in the code — the agent extracts each special case and documents it, so billing doesn't depend on who remembers what.", "personaShift": { "CTO": "documents customer-specific logic", "VPE": "reduces billing-logic errors", "CRO": "reduces revenue-integrity risk", "CFO": "protects billing accuracy" } },
  { "tier": 3, "prompt": "Every time we plan to decommission the old system, we discover something still depends on it.", "pattern": "Undiscoverable dependencies blocking sunset", "rootCause": "Hidden consumers keep the old system alive indefinitely.", "consequence": "Decommissioning never completes; costs persist.", "diagnostic": "Do you have a complete list of everything that still calls the old system?", "angle": "Agents trace all remaining dependencies so the system can actually be retired.", "objection": "We keep finding new dependencies every time we try to shut it off.", "reframe": "The agent inventories every remaining consumer up front, so you retire it once with confidence instead of discovering dependencies the hard way.", "personaShift": { "CFO": "finally ends persistent legacy cost", "CTO": "enables real decommissioning", "VPE": "completes a stalled sunset", "CRO": "reduces risk of a surprise break" } }
];
