export default [
  {
    "tier": 3,
    "prompt": "Our velocity's been dropping for a year and I can't give the board a clean reason why.",
    "pattern": "Aggregate technical-debt drag",
    "rootCause": "Accumulated shortcuts, dead code, inconsistent patterns, missing tests.",
    "consequence": "Declining velocity that's real but hard to articulate to leadership.",
    "diagnostic": "What share of a typical sprint goes to fighting the codebase versus shipping new value?",
    "angle": "Agents attack the debt continuously and in parallel across the estate — this is exactly the Project Coral framing: 'code that slows developers down.'",
    "objection": "Technical debt is too vague to tackle systematically.",
    "reframe": "It feels vague because it's diffuse — but it's made of concrete, findable things: dead code, outdated patterns, missing coverage. Agents work through those at scale, which is what makes the diffuse problem tractable.",
    "personaShift": {
      "VPE": "restores team velocity",
      "CTO": "a board-legible answer to the slowdown",
      "CFO": "recovers lost delivery capacity",
      "CRO": "reduces risk hidden in unmaintained code"
    }
  },
  {
    "tier": 2,
    "prompt": "Every team writes things differently. There's no consistency across the codebase.",
    "pattern": "Pattern inconsistency debt",
    "rootCause": "No enforced standards; divergent conventions across teams.",
    "consequence": "High cognitive load, hard cross-team work, brittle maintenance.",
    "diagnostic": "How much friction do engineers hit when they move between teams' codebases?",
    "angle": "Agents apply consistent patterns across the estate at a scale humans can't sustain manually.",
    "objection": "Getting every team to agree on standards has never worked here.",
    "reframe": "The agent sidesteps the agreement problem by doing the harmonizing work itself — teams review the result rather than fighting over who refactors first.",
    "personaShift": {
      "CTO": "coherent engineering standard",
      "VPE": "smoother cross-team mobility",
      "CFO": "recovers compounding lost delivery capacity",
      "CRO": "reduces risk hidden in unmaintained code"
    }
  },
  {
    "tier": 1,
    "prompt": "We've got a mountain of dead code nobody's brave enough to delete.",
    "pattern": "Dead-code accumulation",
    "rootCause": "Uncertainty about what's still used; deletion feels risky.",
    "consequence": "Bloated codebase, slower builds, higher cognitive load.",
    "diagnostic": "How much of your codebase do you suspect is actually unused — and what would it take to know for sure?",
    "angle": "Agents trace usage and safely remove dead code with tests confirming nothing breaks.",
    "objection": "Deleting old code always breaks something unexpected.",
    "reframe": "Which is why the agent verifies with the test suite before and after removal — you delete with evidence, not hope.",
    "personaShift": {
      "VPE": "leaner, faster codebase",
      "CTO": "reduced surface area and risk",
      "CFO": "recovers compounding lost delivery capacity",
      "CRO": "reduces risk hidden in unmaintained code"
    }
  },
  {
    "tier": 3,
    "prompt": "We keep saying we'll pay down tech debt next quarter, and next quarter never comes.",
    "pattern": "Perpetual debt deferral",
    "rootCause": "Debt work always loses to features because it needs scarce engineer time.",
    "consequence": "Debt compounds indefinitely; velocity keeps eroding.",
    "diagnostic": "How many quarters in a row has 'we'll fix it next quarter' been the plan?",
    "angle": "Agents pay down debt continuously in the background without stealing feature-team capacity.",
    "objection": "We can't spare the engineers to do debt work.",
    "reframe": "That's the whole trap — debt work never wins the capacity fight. Agents break it because they add capacity rather than taking it from feature teams.",
    "personaShift": {
      "VPE": "debt paydown without capacity trade-off",
      "CTO": "breaks the deferral cycle",
      "CFO": "recovers compounding lost velocity",
      "CRO": "reduces risk hidden in unmaintained code"
    }
  },
  {
    "tier": 1,
    "prompt": "Our build times have crept up to the point where developers dread pushing changes.",
    "pattern": "Build / pipeline degradation",
    "rootCause": "Accumulated bloat and inefficiency in build and CI configuration.",
    "consequence": "Slower feedback loops, developer frustration, lost productivity.",
    "diagnostic": "How long does a developer wait from push to feedback now versus a year ago?",
    "angle": "Agents optimize build configuration and remove bloat, restoring fast feedback.",
    "objection": "Build performance is just the cost of a big codebase.",
    "reframe": "Size is part of it, but a lot of build slowness is fixable configuration and dead weight. Agents can systematically trim what's dragging the pipeline.",
    "personaShift": {
      "VPE": "restores developer feedback speed",
      "CFO": "recovers lost engineering hours",
      "CTO": "a board-legible answer to the slowdown",
      "CRO": "reduces risk hidden in unmaintained code"
    }
  },
  {
    "tier": 4,
    "prompt": "We've been told before that a tool would fix our tech debt and it didn't move the needle.",
    "pattern": "Debt-tool disillusionment",
    "rootCause": "Prior tools flagged debt but didn't remediate it, so nothing changed.",
    "consequence": "Skepticism that any tool can actually reduce debt.",
    "diagnostic": "Did the previous tool just measure the debt, or did it actually fix any of it?",
    "angle": "The difference is execution — agents do the remediation work, not just the reporting, and you measure the outcome.",
    "objection": "We've heard 'this will fix your tech debt' before.",
    "reframe": "Most tools measure debt and hand you a dashboard — the work still lands on your engineers. The distinction here is the agent does the remediation itself, so you judge it on debt actually cleared, not a nicer report.",
    "personaShift": {
      "VPE": "remediation not just measurement",
      "CTO": "outcome-based, provable on a pilot",
      "CFO": "pay for debt cleared, not dashboards",
      "CRO": "reduces risk hidden in unmaintained code"
    }
  },
  { "tier": 1, "prompt": "Our codebase has so much copy-paste that one fix has to be made in a dozen places.", "pattern": "Duplication debt", "rootCause": "Widespread copy-paste means logic is repeated instead of shared.", "consequence": "Every change multiplies, and fixes get missed in some copies.", "diagnostic": "When you fix a bug, how many near-identical copies do you have to hunt down?", "angle": "Agents find and consolidate duplicated logic across the codebase.", "objection": "Deduplicating that much code would be a massive undertaking.", "reframe": "Massive and repetitive — the agent identifies the duplicates and consolidates them consistently, verified by tests, at a scale manual cleanup can't reach.", "personaShift": { "VPE": "one fix instead of a dozen", "CTO": "reduces duplication surface", "CFO": "recovers wasted maintenance effort", "CRO": "reduces risk of missed fixes" } },
  { "tier": 1, "prompt": "Our functions are thousands of lines long and nobody wants to touch them.", "pattern": "God-function complexity", "rootCause": "Enormous, tangled functions accumulated over years.", "consequence": "Change is risky and slow anywhere near them.", "diagnostic": "What's the longest function in your codebase, and when did anyone last change it safely?", "angle": "Agents break down and cover monster functions incrementally, with tests confirming behavior.", "objection": "Refactoring those giant functions is bound to break something.", "reframe": "Which is why the agent adds tests around current behavior first, then refactors in verified steps — you get safety before surgery, not a risky rewrite.", "personaShift": { "VPE": "makes untouchable code approachable", "CTO": "reduces complexity risk", "CFO": "recovers velocity lost to complexity", "CRO": "reduces change-breakage risk" } },
  { "tier": 1, "prompt": "Every sprint we add a little more debt because there's never time to do it right.", "pattern": "Debt-accretion habit", "rootCause": "Time pressure makes shortcuts the default in every sprint.", "consequence": "Debt grows steadily and velocity keeps eroding.", "diagnostic": "How much of each sprint's shortcut becomes next quarter's slowdown?", "angle": "Agents pay down debt continuously in the background, offsetting what each sprint adds.", "objection": "There's never capacity to stop and clean up.", "reframe": "That's why manual cleanup never happens. Agents add capacity that pays debt down alongside delivery, so the balance stops tilting the wrong way.", "personaShift": { "VPE": "offsets ongoing debt accretion", "CTO": "stabilizes velocity", "CFO": "protects delivery capacity", "CRO": "keeps risk from compounding" } },
  { "tier": 2, "prompt": "Our velocity charts look fine but everyone knows we're actually slowing down.", "pattern": "Hidden velocity erosion", "rootCause": "Metrics mask the real drag from accumulating debt.", "consequence": "The slowdown is felt but not visible to leadership.", "diagnostic": "What does the team feel about velocity that the charts aren't showing?", "angle": "Agents attack the concrete debt behind the felt slowdown, making improvement measurable.", "objection": "The slowdown is too vague to act on.", "reframe": "It feels vague but it's made of concrete things — long functions, duplication, missing tests. Agents work those down, which turns the felt slowdown into a measurable recovery.", "personaShift": { "VPE": "converts felt drag into fixed causes", "CTO": "makes the slowdown addressable", "CFO": "recovers hidden lost capacity", "CRO": "reduces risk building unseen" } },
  { "tier": 2, "prompt": "Our error handling is inconsistent — some code swallows errors, some crashes, some retries.", "pattern": "Inconsistent error handling", "rootCause": "No shared error strategy; each area does its own thing.", "consequence": "Unpredictable failure behavior and hard debugging.", "diagnostic": "Can you predict how your system will behave when a given error occurs?", "angle": "Agents standardize error handling across the codebase to a consistent, predictable strategy.", "objection": "Retrofitting consistent error handling everywhere is huge.", "reframe": "Huge and repetitive — the agent applies the consistent pattern across every site and verifies behavior, which is exactly the kind of broad, mechanical work it scales on.", "personaShift": { "VPE": "predictable failure behavior", "CTO": "coherent error strategy", "CFO": "reduces debugging cost", "CRO": "reduces risk of silent failures" } },
  { "tier": 2, "prompt": "The real drag is that our code has almost no automated tests, so every change is manual QA.", "pattern": "Test-coverage debt", "rootCause": "Low automated coverage forces slow manual verification.", "consequence": "Every release is a slow, expensive manual QA cycle.", "diagnostic": "How much of your release time is manual QA that automation could replace?", "angle": "Agents write the missing test coverage so verification becomes fast and automated.", "objection": "Writing tests for all this code would take the team forever.", "reframe": "For the team, yes — which is why it never gets done. The agent writes the coverage as part of the work, so QA speeds up without pulling engineers off delivery.", "personaShift": { "VPE": "replaces slow manual QA", "CTO": "builds a real safety net", "CFO": "reduces QA cost", "CRO": "reduces regression risk" } },
  { "tier": 3, "prompt": "Our board wants a number on our technical debt and we can only wave our hands.", "pattern": "Unquantified debt", "rootCause": "No systematic measurement of where and how much debt exists.", "consequence": "Leadership can't prioritize or fund debt work rationally.", "diagnostic": "Could you give the board a concrete inventory of your debt today?", "angle": "Agents inventory the debt into concrete, prioritized items leadership can act on.", "objection": "Technical debt can't really be quantified.", "reframe": "It can be inventoried — dead code, duplication, coverage gaps, complexity hotspots are all countable. The agent produces that concrete list, turning hand-waving into a fundable plan.", "personaShift": { "CFO": "makes debt quantifiable and fundable", "CTO": "turns debt into a concrete backlog", "VPE": "enables rational prioritization", "CRO": "surfaces where risk concentrates" } },
  { "tier": 3, "prompt": "We spend more time working around our own code than building new features.", "pattern": "Workaround tax", "rootCause": "Debt forces constant workarounds instead of clean changes.", "consequence": "A large share of effort produces no new value.", "diagnostic": "What share of a typical change is fighting the codebase versus adding value?", "angle": "Agents remove the debt that forces the workarounds, freeing capacity for real work.", "objection": "Working around the code is just faster than fixing it.", "reframe": "Faster once, slower forever — each workaround adds to the tax. Agents fix the underlying debt so future changes stop paying it.", "personaShift": { "VPE": "reduces the workaround tax", "CTO": "restores clean change paths", "CFO": "recovers effort lost to workarounds", "CRO": "reduces risk of fragile patches" } },
  { "tier": 3, "prompt": "Our debt is concentrated in the exact modules we need to change most often.", "pattern": "Debt in high-churn code", "rootCause": "The most-changed code is also the most debt-laden.", "consequence": "Every frequent change pays a disproportionate debt cost.", "diagnostic": "Do your worst debt hotspots overlap with your highest-churn files?", "angle": "Agents prioritize debt paydown where churn is highest for maximum velocity return.", "objection": "We can't stop changing those modules to clean them up.", "reframe": "You don't stop — the agent cleans them alongside your changes, targeting the high-churn hotspots first so the velocity payoff is immediate.", "personaShift": { "VPE": "biggest velocity return first", "CTO": "targets debt where it hurts most", "CFO": "maximizes cleanup ROI", "CRO": "reduces risk in most-touched code" } },
  { "tier": 4, "prompt": "Leadership says debt work is invisible, so it never gets prioritized over features.", "pattern": "Invisible-work objection", "rootCause": "Debt paydown produces no visible feature, so it loses prioritization.", "consequence": "Debt is never addressed until it causes a crisis.", "diagnostic": "What's the cost when accumulated debt finally causes an outage or a stalled release?", "angle": "Agents make debt paydown continuous and cheap, so it doesn't compete with features for capacity.", "objection": "Debt work is invisible; features always win.", "reframe": "It wins because it costs feature capacity. Agents add capacity for debt paydown, so it stops being an either/or against features — you get both.", "personaShift": { "VPE": "debt paydown without a feature trade-off", "CTO": "keeps the codebase healthy invisibly", "CFO": "avoids crisis-driven remediation cost", "CRO": "prevents debt-driven incidents" } },
  { "tier": 4, "prompt": "Our architects worry an agent cleaning up debt will impose patterns they didn't choose.", "pattern": "Pattern-control concern", "rootCause": "Fear that automated cleanup will override intentional design.", "consequence": "Architects resist automated remediation.", "diagnostic": "Which patterns must any cleanup conform to — and are they defined for the agent to follow?", "angle": "Architects define the target patterns; the agent conforms to them and flags conflicts for review.", "objection": "Automated cleanup will impose patterns we didn't decide on.", "reframe": "The agent follows the patterns your architects define and surfaces anything ambiguous for a decision — it enforces your standards, it doesn't invent its own.", "personaShift": { "CTO": "cleanup that respects your standards", "VPE": "consistent patterns under your control", "CFO": "protects prior design investment", "CRO": "keeps design decisions with humans" } },
  { "tier": 2, "prompt": "Our logging is so noisy and inconsistent that it's useless when we actually need it.", "pattern": "Observability debt", "rootCause": "Inconsistent, noisy logging built up with no strategy.", "consequence": "Debugging is slow because logs can't be trusted.", "diagnostic": "During your last incident, did the logs help or just add noise?", "angle": "Agents standardize and clean up logging so observability actually works.", "objection": "Fixing logging everywhere is tedious and low-priority.", "reframe": "Tedious is the agent's domain — and it's only low-priority until the next incident where useless logs cost you hours. It standardizes logging across the codebase without burdening the team.", "personaShift": { "VPE": "makes logs useful in incidents", "CTO": "restores real observability", "CFO": "reduces debugging cost", "CRO": "improves incident-response evidence" } },
  { "tier": 1, "prompt": "Our dependencies are a tangle where updating one thing forces a cascade of other changes.", "pattern": "Coupling debt", "rootCause": "Tight coupling makes every change ripple widely.", "consequence": "Small changes become large, risky ones.", "diagnostic": "How often does a one-line intent turn into a ten-file change?", "angle": "Agents identify and reduce the coupling that makes changes cascade.", "objection": "Decoupling that code is riskier than living with it.", "reframe": "The agent decouples incrementally behind tests, so each step is verified — reducing the ripple risk you already live with rather than adding to it.", "personaShift": { "VPE": "makes changes local again", "CTO": "reduces harmful coupling", "CFO": "reduces cost of ballooning changes", "CRO": "reduces cascade-failure risk" } },
  { "tier": 3, "prompt": "We've tried debt sprints but they never make a lasting dent before features take over again.", "pattern": "Ineffective debt sprints", "rootCause": "Periodic sprints can't outpace continuous debt accretion.", "consequence": "Temporary gains erased before the next sprint.", "diagnostic": "How long do the gains from a debt sprint last before they're swallowed again?", "angle": "Agents make debt paydown continuous rather than a periodic sprint that never keeps up.", "objection": "We do dedicate time to debt; it just doesn't stick.", "reframe": "Periodic sprints can't beat continuous accretion. Agents pay debt down continuously in the background, so the dent is sustained rather than erased between sprints.", "personaShift": { "VPE": "sustained rather than temporary gains", "CTO": "continuous instead of periodic paydown", "CFO": "protects the cleanup investment", "CRO": "keeps risk trending down" } },
  { "tier": 2, "prompt": "Our database schema has accumulated columns and tables nobody's sure are still needed.", "pattern": "Schema debt", "rootCause": "Schema grew without cleanup; unused structures linger.", "consequence": "Confusing data model and risky migrations.", "diagnostic": "How many columns in your core tables do you suspect are unused?", "angle": "Agents analyze usage to identify and safely retire unused schema elements.", "objection": "Touching the schema is too risky to bother.", "reframe": "The agent verifies each element is truly unused before proposing removal, with tests — so schema cleanup becomes evidence-based rather than the gamble you're avoiding.", "personaShift": { "CTO": "clarifies the data model", "VPE": "simplifies migrations", "CFO": "reduces storage and maintenance cost", "CRO": "reduces risk of confusing data" } },
  { "tier": 4, "prompt": "Our team says our debt is too far gone for any cleanup to matter.", "pattern": "Debt-fatalism objection", "rootCause": "Belief that the debt is beyond meaningful improvement.", "consequence": "No effort is made because it feels hopeless.", "diagnostic": "What if a single high-churn module measurably improved in a couple of weeks?", "angle": "Prove it on one painful, high-churn area so the team sees measurable improvement is possible.", "objection": "Our codebase is too far gone to fix.", "reframe": "You don't fix it all at once — you prove it on one painful module. When the team sees measurable improvement there, 'too far gone' becomes 'where do we point it next.'", "personaShift": { "VPE": "restores belief via a visible win", "CTO": "proves improvement is achievable", "CFO": "starts ROI on a bounded slice", "CRO": "begins reducing concentrated risk" } },
  { "tier": 1, "prompt": "Our CI pipeline is flaky and everyone's learned to just re-run it until it passes.", "pattern": "Flaky-test debt", "rootCause": "Unreliable tests erode trust in the pipeline.", "consequence": "Real failures get ignored amid the noise.", "diagnostic": "How often does your team re-run CI assuming a failure is just flakiness?", "angle": "Agents diagnose and fix flaky tests so CI signal becomes trustworthy again.", "objection": "Flaky tests are just part of having a big test suite.", "reframe": "Flakiness is fixable — timing, ordering, shared state. The agent diagnoses and repairs the flaky tests, so a red build means something again.", "personaShift": { "VPE": "restores trust in CI", "CTO": "makes the pipeline reliable", "CFO": "reduces wasted re-run cycles", "CRO": "stops real failures hiding in noise" } },
  { "tier": 3, "prompt": "Performance has degraded over years of small changes and we can't point to one cause.", "pattern": "Diffuse performance debt", "rootCause": "Many small inefficiencies accumulated with no single culprit.", "consequence": "Steady performance decline that's hard to attribute.", "diagnostic": "How much slower is the system now than two years ago, and where did it go?", "angle": "Agents systematically find and fix the many small inefficiencies dragging performance.", "objection": "There's no single fix; performance issues are everywhere.", "reframe": "Everywhere-but-small is exactly the diffuse problem agents handle — they work through the many inefficiencies systematically, which no single manual fix could.", "personaShift": { "VPE": "restores system performance", "CTO": "addresses diffuse degradation", "CFO": "reduces infra cost from inefficiency", "CRO": "reduces risk of performance incidents" } },
  { "tier": 2, "prompt": "Our code comments and docs contradict what the code actually does now.", "pattern": "Documentation-code drift", "rootCause": "Docs and comments weren't updated as code evolved.", "consequence": "Developers are actively misled by wrong documentation.", "diagnostic": "How often does your team get misled by a comment that no longer matches the code?", "angle": "Agents reconcile documentation with actual code behavior and keep it current.", "objection": "Outdated comments are harmless; people ignore them.", "reframe": "They're not ignored when they mislead someone into a bug. The agent reconciles docs to the real behavior, so comments help rather than harm.", "personaShift": { "VPE": "removes misleading documentation", "CTO": "aligns docs with reality", "CFO": "reduces cost of misled changes", "CRO": "reduces risk from wrong guidance" } },
  { "tier": 1, "prompt": "We have three different ways of doing the same thing because standards changed over time.", "pattern": "Convention drift", "rootCause": "Evolving standards left multiple coexisting approaches.", "consequence": "Cognitive load and inconsistency across the codebase.", "diagnostic": "How many different ways does your codebase solve the same common problem?", "angle": "Agents converge the codebase on the current standard consistently.", "objection": "Standardizing all the old code isn't worth the churn.", "reframe": "The agent converges it incrementally and verifiably, so the churn is controlled — and every future change gets easier for developers who no longer guess which pattern applies.", "personaShift": { "VPE": "reduces cognitive load", "CTO": "restores a single standard", "CFO": "reduces maintenance friction", "CRO": "reduces inconsistency risk" } },
  { "tier": 3, "prompt": "Our infrastructure code has drifted so far from reality that nobody trusts it.", "pattern": "Infrastructure-as-code drift", "rootCause": "Manual changes diverged from the IaC definitions.", "consequence": "IaC can't be trusted, so it's bypassed, worsening drift.", "diagnostic": "If you applied your IaC as-is today, how much would break versus current reality?", "angle": "Agents reconcile the IaC with actual infrastructure so it becomes trustworthy again.", "objection": "Reconciling all that drift is more effort than it's worth.", "reframe": "Drift compounds until an incident forces the reckoning. The agent reconciles it systematically now, restoring IaC you can trust before it costs you an outage.", "personaShift": { "CTO": "restores trustworthy IaC", "VPE": "makes infra changes safe again", "CFO": "reduces cost of manual infra work", "CRO": "reduces infra-drift risk" } },
  { "tier": 2, "prompt": "Our feature flags never get cleaned up so the code is full of dead branches.", "pattern": "Feature-flag debt", "rootCause": "Flags are added but never removed after rollout.", "consequence": "Dead branches clutter and confuse the codebase.", "diagnostic": "How many of your feature flags are permanently on or off but still in the code?", "angle": "Agents identify stale flags and remove the dead branches safely.", "objection": "Cleaning up flags risks removing something still in use.", "reframe": "The agent checks each flag's actual state and usage before removing its dead branches, verified by tests — so cleanup is safe, not a guess.", "personaShift": { "VPE": "removes dead branches", "CTO": "reduces code clutter", "CFO": "reduces maintenance overhead", "CRO": "reduces risk of stale-flag surprises" } },
  { "tier": 4, "prompt": "Finance won't fund debt work because it doesn't show up as revenue or a feature.", "pattern": "Funding-model objection", "rootCause": "Debt paydown doesn't fit revenue-or-feature funding categories.", "consequence": "Necessary work is structurally unfundable.", "diagnostic": "What's the revenue lost to slowed delivery that the debt is quietly causing?", "angle": "Frame debt paydown as recovered delivery capacity — measurable velocity that funds itself.", "objection": "Debt work doesn't produce revenue, so we won't fund it.", "reframe": "It produces recovered velocity — features shipped faster because the drag is gone. Measured that way, debt paydown is a revenue enabler, not a cost center.", "personaShift": { "CFO": "reframes debt work as capacity ROI", "CTO": "ties cleanup to delivery speed", "VPE": "recovers measurable velocity", "CRO": "reduces cost of unmanaged risk" } },
  { "tier": 3, "prompt": "New features keep taking longer to build and we can't explain why to the business.", "pattern": "Rising feature-delivery cost", "rootCause": "Accumulating debt makes each new feature more expensive.", "consequence": "The business sees slowing delivery with no clear reason.", "diagnostic": "How much longer does a comparable feature take now than a year or two ago?", "angle": "Agents reduce the debt inflating feature cost, restoring predictable delivery.", "objection": "Features are just getting more complex; that's expected.", "reframe": "Some of it is complexity, but a lot is debt tax on every change. Agents cut that tax, so delivery cost stops creeping for reasons the business can't see.", "personaShift": { "VPE": "restores predictable delivery", "CTO": "explains and reverses the slowdown", "CFO": "controls rising delivery cost", "CRO": "reduces risk in an aging codebase" } },
  { "tier": 1, "prompt": "Our codebase is full of TODO and FIXME comments going back years that nobody addresses.", "pattern": "Deferred-fix backlog", "rootCause": "Known issues were flagged but never resolved.", "consequence": "A visible backlog of acknowledged problems festering in the code.", "diagnostic": "How many years-old FIXMEs are sitting in your codebase right now?", "angle": "Agents work through the flagged issues systematically, resolving the known-debt backlog.", "objection": "Most of those TODOs aren't worth revisiting.", "reframe": "The agent triages them — resolving the real ones and clearing the obsolete ones — so the backlog reflects reality instead of accreting forever.", "personaShift": { "VPE": "clears a festering backlog", "CTO": "resolves acknowledged issues", "CFO": "reduces latent maintenance cost", "CRO": "closes known-issue risk" } },
  { "tier": 2, "prompt": "Our microservices share so much copy-pasted boilerplate that fixes never reach all of them.", "pattern": "Cross-service duplication", "rootCause": "Boilerplate copied across services instead of shared.", "consequence": "Fixes and improvements don't propagate consistently.", "diagnostic": "When you improve shared boilerplate, how many services actually get the update?", "angle": "Agents consolidate shared boilerplate or propagate fixes across all services consistently.", "objection": "Each service's copy has diverged too much to unify.", "reframe": "The agent reconciles the divergences and either consolidates or propagates fixes across every service — handling exactly the divergence that makes manual unification impractical.", "personaShift": { "VPE": "fixes propagate everywhere", "CTO": "reduces cross-service duplication", "CFO": "reduces multiplied maintenance", "CRO": "reduces inconsistent-fix risk" } },
  { "tier": 3, "prompt": "We know we have debt but we don't know which of it actually matters.", "pattern": "Unprioritized debt", "rootCause": "No way to distinguish high-impact debt from harmless cruft.", "consequence": "Effort risks going to debt that doesn't matter.", "diagnostic": "Could you rank your debt by actual impact on delivery and risk today?", "angle": "Agents assess debt by churn, complexity, and risk to prioritize what actually matters.", "objection": "All debt feels equally daunting; we don't know where to start.", "reframe": "The agent ranks it by real signals — how often code changes, how complex it is, where risk sits — so you start with the debt that pays back, not the loudest.", "personaShift": { "CTO": "prioritizes high-impact debt", "VPE": "focuses effort where it counts", "CFO": "maximizes cleanup ROI", "CRO": "targets the riskiest debt first" } },
  { "tier": 1, "prompt": "Our build produces dozens of warnings that everyone has learned to scroll past.", "pattern": "Warning blindness", "rootCause": "Accumulated warnings desensitized the team to all of them.", "consequence": "Real warnings hide among the ignored ones.", "diagnostic": "How many build warnings do you have, and when did anyone last act on one?", "angle": "Agents resolve the accumulated warnings so new ones stand out and get addressed.", "objection": "Those warnings are harmless; they've never caused a problem.", "reframe": "Until one does and it's buried in the noise. The agent clears the backlog so warnings become signal again — cheap insurance against the one that matters.", "personaShift": { "VPE": "restores warnings as signal", "CTO": "cleans the build output", "CFO": "reduces risk of ignored issues", "CRO": "surfaces real warnings" } },
  { "tier": 2, "prompt": "Our async and concurrency code is a minefield nobody fully reasons about.", "pattern": "Concurrency debt", "rootCause": "Ad-hoc concurrency patterns accumulated without a coherent model.", "consequence": "Rare, hard-to-reproduce bugs and fear of touching the code.", "diagnostic": "How confident is your team reasoning about your concurrency code under load?", "angle": "Agents document and rationalize the concurrency patterns and add tests around them.", "objection": "Concurrency bugs are too subtle for anything to safely fix.", "reframe": "Subtlety is why methodical analysis helps — the agent maps the concurrency patterns, documents the invariants, and adds tests, making the minefield reason-about-able.", "personaShift": { "VPE": "makes concurrency code approachable", "CTO": "rationalizes concurrency patterns", "CFO": "reduces cost of rare hard bugs", "CRO": "reduces risk of concurrency failures" } }
];
