export default [
  {
    "tier": 3,
    "prompt": "Our database version goes end-of-support next year and audit is already asking.",
    "pattern": "Compliance-forced modernization",
    "rootCause": "External deadline; pure risk-avoidance with no business ROI on its own.",
    "consequence": "Must-do work, resented cost, audit pressure mounting.",
    "diagnostic": "Is this the only end-of-support deadline on your horizon, or the first of several coming?",
    "angle": "Agents make mandatory, low-glory modernization dramatically cheaper and faster.",
    "objection": "This is just a cost we have to eat; there's no upside.",
    "reframe": "The upside is doing it for a fraction of the cost and time — and once the agent capability is in place, the next three end-of-support deadlines stop being fire drills.",
    "personaShift": {
      "CRO": "satisfies audit and control requirements",
      "CFO": "minimizes unavoidable spend",
      "CTO": "clears mandated work without derailing the roadmap",
      "VPE": "spares the team a forced manual slog"
    }
  },
  {
    "tier": 2,
    "prompt": "New regulation means we have to prove data lineage across systems we barely understand.",
    "pattern": "Regulatory traceability mandate",
    "rootCause": "Compliance requires understanding of systems that are undocumented.",
    "consequence": "Regulatory exposure; manual discovery is slow and costly.",
    "diagnostic": "How confident are you that you could produce that lineage today if the regulator asked tomorrow?",
    "angle": "Agents analyze and document data flows across systems to produce the traceability evidence.",
    "objection": "This is a compliance problem, not a coding problem.",
    "reframe": "The compliance answer depends on understanding the code and data flows — which is a code problem underneath. The agent produces the technical evidence your compliance team needs.",
    "personaShift": {
      "CRO": "produces auditable lineage evidence",
      "CTO": "turns an opaque estate legible for compliance",
      "VPE": "spares the team a forced manual slog",
      "CFO": "minimizes unavoidable compliance spend"
    }
  },
  {
    "tier": 4,
    "prompt": "Compliance work is manual here because auditors want a human accountable for every change.",
    "pattern": "Human-accountability requirement",
    "rootCause": "Belief that automation removes the accountable human.",
    "consequence": "Modernization stays slow and manual under compliance framing.",
    "diagnostic": "Does the auditor require a human to make the change, or a human to be accountable for approving it?",
    "angle": "The agent proposes; a named human approves through the existing control — accountability is preserved, speed is added.",
    "objection": "Auditors want a human accountable for every change.",
    "reframe": "And there still is one — the approver. The agent doesn't merge anything; your engineer signs off through the same gate. You keep the accountable human and remove only the manual labor.",
    "personaShift": {
      "CRO": "accountability chain intact",
      "VPE": "removes manual toil, keeps control",
      "CTO": "clears mandated work without derailing roadmap",
      "CFO": "minimizes unavoidable compliance spend"
    }
  },
  {
    "tier": 1,
    "prompt": "An acquisition means we have to integrate two totally different tech stacks fast.",
    "pattern": "M&A integration pressure",
    "rootCause": "Post-acquisition mandate to integrate disparate, unfamiliar systems quickly.",
    "consequence": "Time-pressured integration of systems neither team fully understands.",
    "diagnostic": "What's the deadline for integration, and who actually understands the acquired stack?",
    "angle": "Agents analyze and document the unfamiliar codebase and accelerate the integration work.",
    "objection": "Nobody on our side understands the acquired system yet.",
    "reframe": "That's precisely where an agent helps first — it reads and documents the acquired codebase so your team gains understanding fast, before any integration work begins.",
    "personaShift": {
      "CTO": "accelerates integration timeline",
      "CFO": "realizes deal synergies faster",
      "CRO": "reduces integration risk",
      "VPE": "spares the team a forced manual slog"
    }
  },
  {
    "tier": 2,
    "prompt": "Accessibility regulations now require us to retrofit hundreds of old screens.",
    "pattern": "Regulatory retrofit at scale",
    "rootCause": "New compliance standard applied to a large volume of legacy UI.",
    "consequence": "Large, mandatory, repetitive remediation with a deadline.",
    "diagnostic": "How many screens are in scope, and what's your current pace to remediate one?",
    "angle": "Agents apply the required changes across hundreds of screens in parallel, consistently.",
    "objection": "This is a huge amount of tedious manual work.",
    "reframe": "Tedious, repetitive, and consistent — which is the ideal agent task. It applies the same remediation across every screen at once while your team spot-checks the output.",
    "personaShift": {
      "CRO": "meets the accessibility mandate",
      "CFO": "minimizes the cost of forced retrofit",
      "VPE": "spares the team a soul-crushing manual slog",
      "CTO": "clears mandated work without derailing roadmap"
    }
  },
  { "tier": 1, "prompt": "PCI DSS requires us to modernize how we handle card data across dozens of systems.", "pattern": "PCI-driven modernization", "rootCause": "A payment-security standard mandates changes across many systems.", "consequence": "Mandatory, deadline-bound work with audit consequences.", "diagnostic": "How many systems touch card data, and do you know them all?", "angle": "Agents inventory every system touching card data and apply the required changes consistently.", "objection": "Finding everywhere card data flows is a project in itself.", "reframe": "That discovery is exactly what the agent does first — tracing card-data flows across the estate — so remediation targets everything, not just what you remembered.", "personaShift": { "CRO": "satisfies PCI DSS requirements", "CFO": "minimizes unavoidable compliance spend", "CTO": "clears mandated work without derailing the roadmap", "VPE": "spares the team a manual audit slog" } },
  { "tier": 1, "prompt": "SOX controls require change traceability our older systems just can't produce.", "pattern": "SOX traceability gap", "rootCause": "Legacy systems lack the change-tracking controls SOX demands.", "consequence": "Audit findings and manual evidence-gathering every cycle.", "diagnostic": "Can you produce a clean change-audit trail for those systems today?", "angle": "Agents implement the traceability and generate the audit evidence the controls require.", "objection": "Retrofitting audit trails into old systems is enormous.", "reframe": "Enormous and mechanical — the agent implements the traceability across systems and produces the evidence, turning a recurring audit scramble into standing controls.", "personaShift": { "CRO": "satisfies SOX control requirements", "CFO": "reduces recurring audit cost", "CTO": "clears mandated work without derailing roadmap", "VPE": "ends the manual evidence scramble" } },
  { "tier": 1, "prompt": "GDPR means we have to be able to delete a customer's data everywhere, and we can't.", "pattern": "Right-to-erasure gap", "rootCause": "Data is scattered with no way to comprehensively delete it.", "consequence": "Non-compliance risk with significant potential penalties.", "diagnostic": "If a customer demanded full erasure today, could you guarantee it everywhere?", "angle": "Agents map where personal data lives across systems and implement compliant deletion.", "objection": "We don't even know everywhere customer data ends up.", "reframe": "The agent traces personal data across your systems to build that map — which is the prerequisite for compliant erasure you're currently missing.", "personaShift": { "CRO": "enables compliant right-to-erasure", "CFO": "avoids GDPR penalty exposure", "CTO": "makes data governance enforceable", "VPE": "spares the team a manual data hunt" } },
  { "tier": 1, "prompt": "New DORA rules require us to prove operational resilience for our critical systems.", "pattern": "DORA resilience mandate", "rootCause": "Regulation demands demonstrable resilience the systems can't yet show.", "consequence": "Regulatory obligation with a hard compliance timeline.", "diagnostic": "Could you demonstrate operational resilience for your critical systems to a regulator now?", "angle": "Agents document dependencies and implement the resilience evidence DORA requires.", "objection": "Proving resilience across our estate is a huge undertaking.", "reframe": "The agent maps critical-system dependencies and produces the resilience documentation and controls — doing the exhaustive discovery that makes the mandate achievable.", "personaShift": { "CRO": "satisfies DORA resilience requirements", "CFO": "minimizes unavoidable compliance spend", "CTO": "makes resilience demonstrable", "VPE": "spares the team a manual mapping slog" } },
  { "tier": 2, "prompt": "The real problem is our compliance evidence is assembled by hand every audit and it's exhausting.", "pattern": "Manual evidence assembly", "rootCause": "No automated way to produce compliance evidence from the systems.", "consequence": "Every audit is a costly, repeated manual effort.", "diagnostic": "How many person-weeks does each audit cost you in evidence-gathering alone?", "angle": "Agents generate compliance evidence directly from the systems, making audits repeatable and cheap.", "objection": "Audit evidence has to be assembled by people who understand the systems.", "reframe": "It has to be reviewed by them — but the agent assembles the evidence from the systems for review, turning weeks of manual gathering into hours of verification.", "personaShift": { "CRO": "produces repeatable audit evidence", "CFO": "cuts recurring audit cost", "CTO": "makes compliance evidence systematic", "VPE": "frees the team from audit grind" } },
  { "tier": 2, "prompt": "A new regulation applies to code we no longer understand, so we can't even assess compliance.", "pattern": "Compliance against opaque code", "rootCause": "Can't assess compliance of systems nobody understands.", "consequence": "Unknown compliance exposure in critical systems.", "diagnostic": "How can you assess compliance of a system you can't currently explain?", "angle": "Agents document the opaque systems so compliance can be assessed and gaps remediated.", "objection": "We can't assess what we don't understand.", "reframe": "Exactly — so the agent restores the understanding first, documenting what the system does, which is the prerequisite for any compliance assessment.", "personaShift": { "CRO": "enables compliance assessment", "CTO": "makes opaque systems assessable", "CFO": "reduces unknown compliance exposure", "VPE": "spares a manual reverse-engineering effort" } },
  { "tier": 2, "prompt": "Our compliance deadline is fixed but the work depends on understanding legacy we haven't documented.", "pattern": "Deadline gated by understanding", "rootCause": "Remediation can't start until the legacy is understood, and time is short.", "consequence": "The deadline is at risk before real work even begins.", "diagnostic": "How much of your remaining time will just go to understanding the systems?", "angle": "Agents compress the understanding phase so remediation starts sooner and the deadline holds.", "objection": "We'll spend all our time just figuring out the systems.", "reframe": "That's the phase agents shorten most — rapidly documenting the legacy so your team spends the remaining time remediating, not deciphering.", "personaShift": { "CRO": "protects the compliance deadline", "CTO": "compresses the discovery phase", "CFO": "avoids missed-deadline penalties", "VPE": "gives the team time to actually remediate" } },
  { "tier": 3, "prompt": "Every new regulation means another expensive fire drill for our engineering team.", "pattern": "Recurring compliance fire drills", "rootCause": "No reusable capability, so each mandate is handled from scratch.", "consequence": "Repeated disruption and cost with every new rule.", "diagnostic": "How many compliance fire drills has your team absorbed in the last two years?", "angle": "Agents build a reusable remediation capability so each new mandate stops being a fresh fire drill.", "objection": "Compliance changes are unpredictable; you can't prepare for them.", "reframe": "You can't predict the rule, but you can build the muscle — once agents can inventory and remediate the estate, each new mandate becomes a routine application, not a crisis.", "personaShift": { "CTO": "builds a reusable compliance capability", "CRO": "responds to mandates routinely", "CFO": "reduces per-mandate cost", "VPE": "ends the recurring fire drills" } },
  { "tier": 3, "prompt": "Auditors flagged that we can't demonstrate segregation of duties in our older systems.", "pattern": "Segregation-of-duties gap", "rootCause": "Legacy systems lack enforceable, demonstrable duty separation.", "consequence": "A recurring audit finding with compliance risk.", "diagnostic": "Could you show an auditor exactly how duties are separated and enforced in those systems?", "angle": "Agents document and implement the controls that make segregation of duties demonstrable.", "objection": "Adding those controls to old systems risks breaking them.", "reframe": "The agent implements the controls incrementally with verification, so you gain demonstrable segregation of duties without the risky big-bang change you fear.", "personaShift": { "CRO": "closes a segregation-of-duties finding", "CTO": "makes controls demonstrable", "CFO": "reduces recurring audit-finding cost", "VPE": "adds controls without disruption" } },
  { "tier": 4, "prompt": "Our compliance officer insists only humans, not tools, can be trusted with regulated changes.", "pattern": "Human-only-trust objection", "rootCause": "Belief that regulated changes must be entirely human-performed.", "consequence": "Modernization of regulated systems stays slow and manual.", "diagnostic": "Does the regulation require a human to perform the change, or to approve and be accountable for it?", "angle": "The agent proposes; a named human approves through existing controls — accountability stays human, speed is added.", "objection": "Regulated changes can't be trusted to a tool.", "reframe": "The tool doesn't own the change — your compliance-accountable human approves it through the same gate. You keep human trust and accountability; you just remove the manual labor.", "personaShift": { "CRO": "accountability stays with humans", "CTO": "no change to the control model", "CFO": "reduces manual compliance cost", "VPE": "removes toil while keeping oversight" } },
  { "tier": 4, "prompt": "Leadership sees compliance modernization as pure cost with zero business return.", "pattern": "Cost-center framing", "rootCause": "Compliance work is viewed as spend with no upside.", "consequence": "It's funded grudgingly and minimally, raising risk.", "diagnostic": "What does a failed audit or breach cost compared to doing this properly?", "angle": "Agents cut the cost dramatically and the modernized systems yield reuse beyond compliance.", "objection": "Compliance spend never returns anything to the business.", "reframe": "The return is avoided penalties and breaches — and modernizing for compliance often leaves systems more maintainable and reusable, so the spend does more than tick a box.", "personaShift": { "CFO": "minimizes cost and captures side benefits", "CRO": "reduces penalty and breach exposure", "CTO": "leaves systems more maintainable", "VPE": "reduces future compliance toil" } },
  { "tier": 2, "prompt": "New data-residency rules mean we have to know exactly where all our data physically lives.", "pattern": "Data-residency mandate", "rootCause": "Regulation requires precise knowledge of data location the org lacks.", "consequence": "Compliance risk from unknown data placement.", "diagnostic": "Could you prove where each category of your data physically resides today?", "angle": "Agents trace data flows and storage to map residency and flag non-compliant placement.", "objection": "Tracking where all our data lives is beyond us right now.", "reframe": "The agent traces data across systems to produce the residency map — the exhaustive tracking that's impractical by hand is exactly its strength.", "personaShift": { "CRO": "proves data-residency compliance", "CTO": "makes data placement visible", "CFO": "avoids residency-violation penalties", "VPE": "spares a manual data-tracing effort" } },
  { "tier": 1, "prompt": "An industry standard we sell into now requires certifications our codebase can't currently meet.", "pattern": "Market-access certification", "rootCause": "A certification gate blocks selling into a market.", "consequence": "Lost revenue until the certification requirements are met.", "diagnostic": "What revenue is blocked until you meet that certification?", "angle": "Agents remediate the codebase to meet the certification requirements faster.", "objection": "Meeting that certification is a long, expensive road.", "reframe": "Agents shorten it by applying the required changes across the codebase in parallel — turning a road that blocks revenue into a faster path to market.", "personaShift": { "CTO": "meets certification requirements", "CFO": "unblocks certification-gated revenue", "CRO": "achieves compliant market access", "VPE": "delivers the remediation efficiently" } },
  { "tier": 3, "prompt": "We passed the audit last year but only by heroics we can't sustain every cycle.", "pattern": "Unsustainable compliance", "rootCause": "Compliance depends on unsustainable manual heroics.", "consequence": "Each cycle risks failure as the heroics can't scale.", "diagnostic": "What happens the cycle your team can't pull off the heroics again?", "angle": "Agents make compliance a repeatable, automated process instead of an annual heroic effort.", "objection": "We got through it; why change what works?", "reframe": "It works until the heroics run out. Making compliance repeatable with agents removes the dependence on unsustainable effort before a cycle fails.", "personaShift": { "CRO": "makes compliance sustainable", "CTO": "automates a heroic manual process", "CFO": "reduces cost and risk each cycle", "VPE": "ends unsustainable crunch" } },
  { "tier": 2, "prompt": "A regulator now requires encryption we didn't build into our older data stores.", "pattern": "Retrofit-encryption mandate", "rootCause": "Older stores lack the encryption the regulation now demands.", "consequence": "Mandatory remediation across many data stores.", "diagnostic": "How many data stores need encryption retrofitted, and are they all identified?", "angle": "Agents identify unencrypted stores and implement compliant encryption across them.", "objection": "Retrofitting encryption everywhere risks breaking access.", "reframe": "The agent applies the encryption changes with verification across each store, catching access issues in testing — so you meet the mandate without breaking production.", "personaShift": { "CRO": "meets the encryption mandate", "CTO": "retrofits encryption safely", "CFO": "minimizes forced-remediation cost", "VPE": "spares a manual store-by-store slog" } },
  { "tier": 4, "prompt": "Our risk team says introducing agents into a regulated pipeline is itself a compliance risk.", "pattern": "Agent-as-compliance-risk objection", "rootCause": "Concern that the agent adds an unmanaged compliance surface.", "consequence": "Compliance framing blocks the very work it needs.", "diagnostic": "What controls would any new contributor to that pipeline have to satisfy?", "angle": "The agent operates within existing controls as a scoped, auditable identity — no new compliance surface.", "objection": "Adding agents to a regulated pipeline creates new compliance risk.", "reframe": "It works inside your existing controls — scoped access, reviewed changes, audit trail — like any contributor. There's no new surface; the control environment is unchanged.", "personaShift": { "CRO": "operates within existing controls", "CTO": "no new compliance surface", "CFO": "avoids bespoke control cost", "VPE": "keeps the pipeline's gates intact" } },
  { "tier": 3, "prompt": "A regulatory change requires us to update the same logic across dozens of jurisdictions' variants.", "pattern": "Multi-jurisdiction rule change", "rootCause": "The same rule change must apply across many localized variants.", "consequence": "Repetitive, error-prone changes across jurisdictions.", "diagnostic": "How many jurisdictional variants have to change, and how do you keep them consistent?", "angle": "Agents apply the rule change consistently across every jurisdictional variant and verify each.", "objection": "Each jurisdiction's variant is subtly different; it's error-prone.", "reframe": "Subtle-but-repetitive is the agent's strength — it applies the change per variant, respecting each difference, and verifies, which is far less error-prone than manual edits.", "personaShift": { "CRO": "compliant across all jurisdictions", "CTO": "consistent multi-variant changes", "CFO": "reduces cost of jurisdictional work", "VPE": "removes error-prone repetition" } },
  { "tier": 1, "prompt": "Regulators are phasing out a protocol we still rely on and we must move off it.", "pattern": "Protocol-deprecation mandate", "rootCause": "A regulator-mandated protocol sunset forces migration.", "consequence": "A hard deadline to replace a widely-used protocol.", "diagnostic": "Everywhere that protocol is used — do you have the full list, and the deadline?", "angle": "Agents find every use of the deprecated protocol and migrate to the compliant replacement.", "objection": "That protocol is used in more places than we can track.", "reframe": "The agent inventories every usage across the estate and migrates each — the comprehensive discovery is what makes hitting the mandate feasible.", "personaShift": { "CRO": "meets the protocol-sunset mandate", "CTO": "migrates off a deprecated protocol", "CFO": "avoids non-compliance penalties", "VPE": "removes manual usage-hunting" } },
  { "tier": 2, "prompt": "Our audit trail has gaps because different systems log differently and some barely log at all.", "pattern": "Inconsistent audit logging", "rootCause": "No consistent logging standard across systems for audit purposes.", "consequence": "Incomplete audit trails that fail scrutiny.", "diagnostic": "If an auditor asked for a full trail of a transaction, could every system provide its part?", "angle": "Agents standardize audit logging across systems to close the gaps.", "objection": "Standardizing logging across all those systems is too much work.", "reframe": "It's broad and repetitive — the agent applies consistent audit logging across every system, closing the gaps that a manual effort would take months to reach.", "personaShift": { "CRO": "produces complete audit trails", "CTO": "standardizes audit logging", "CFO": "reduces audit-failure cost", "VPE": "spares a system-by-system logging slog" } },
  { "tier": 3, "prompt": "We're told to modernize for compliance but leadership wants to know it won't disrupt the business.", "pattern": "Disruption-averse mandate", "rootCause": "Compliance work must proceed without disrupting operations.", "consequence": "Tension between mandatory change and business continuity.", "diagnostic": "What's the business's tolerance for disruption during this compliance work?", "angle": "Agents work incrementally with verification, so compliance changes land without business disruption.", "objection": "Any change to those systems risks disrupting the business.", "reframe": "Incremental, tested changes are how you comply without disruption — the agent verifies each step, so the mandate is met while operations keep running.", "personaShift": { "CRO": "meets the mandate safely", "CTO": "changes without disruption", "CFO": "avoids downtime cost", "VPE": "keeps the business running during remediation" } },
  { "tier": 1, "prompt": "New rules require detailed model-risk documentation for algorithms we never documented.", "pattern": "Model-risk documentation mandate", "rootCause": "Regulation requires documentation of models that lack it.", "consequence": "Compliance gap on algorithmic decision-making.", "diagnostic": "Could you produce model-risk documentation for your key algorithms today?", "angle": "Agents document the models' logic and behavior to satisfy the model-risk requirements.", "objection": "Our models are too complex to document to that standard.", "reframe": "The agent analyzes the model code and behavior to produce the documentation for your experts to review — handling the volume that makes manual documentation infeasible.", "personaShift": { "CRO": "satisfies model-risk requirements", "CTO": "documents algorithmic logic", "CFO": "avoids compliance penalties", "VPE": "spares the team a documentation slog" } },
  { "tier": 4, "prompt": "Our board fears that automating compliance work will look like cutting corners to regulators.", "pattern": "Perception-of-corner-cutting objection", "rootCause": "Fear that automation signals reduced rigor to regulators.", "consequence": "Manual approaches are kept for optics, not effectiveness.", "diagnostic": "Would regulators prefer consistent, auditable automated controls or inconsistent manual ones?", "angle": "Automated, auditable controls are more rigorous than manual effort — the opposite of cutting corners.", "objection": "Automating compliance will look like we're cutting corners.", "reframe": "Regulators favor consistency and evidence. Automated controls with a full audit trail are more rigorous and more defensible than error-prone manual work — it's raising the bar, not lowering it.", "personaShift": { "CRO": "stronger, auditable controls", "CTO": "more rigor, not less", "CFO": "defensible and cheaper", "VPE": "consistent controls without toil" } },
  { "tier": 2, "prompt": "A new standard requires us to prove our third-party components are secure and current.", "pattern": "Supply-chain compliance", "rootCause": "Regulation demands assurance over third-party dependencies.", "consequence": "Compliance risk from unmanaged third-party components.", "diagnostic": "Could you produce a current, complete inventory of your third-party components and their status?", "angle": "Agents inventory dependencies, assess their status, and remediate non-compliant ones.", "objection": "We don't have a full picture of our third-party components.", "reframe": "The agent builds that inventory and assesses each component against the standard — the comprehensive picture you're missing is the first thing it produces.", "personaShift": { "CRO": "proves supply-chain compliance", "CTO": "makes dependencies visible", "CFO": "avoids supply-chain penalties", "VPE": "spares a manual dependency audit" } },
  { "tier": 3, "prompt": "Our compliance backlog keeps growing because remediation is slower than new requirements arrive.", "pattern": "Compliance-backlog growth", "rootCause": "Manual remediation can't keep pace with incoming requirements.", "consequence": "A widening gap between obligations and remediation.", "diagnostic": "Is your compliance backlog shrinking or growing quarter over quarter?", "angle": "Agents add remediation capacity so the backlog stops outpacing the team.", "objection": "We can't hire fast enough to keep up with compliance demands.", "reframe": "Hiring can't close a widening gap. Agents add remediation capacity that scales with the requirements, so the backlog stops growing faster than you can address it.", "personaShift": { "CRO": "closes a widening compliance gap", "CTO": "adds remediation capacity", "CFO": "reduces cost of backlog growth", "VPE": "relieves an overwhelmed team" } },
  { "tier": 1, "prompt": "Accessibility law now requires our public services to meet standards our old sites fail.", "pattern": "Accessibility legal mandate", "rootCause": "Legally-required accessibility standards apply to non-compliant sites.", "consequence": "Legal exposure and a deadline to remediate public services.", "diagnostic": "How many of your public pages currently fail the required accessibility standard?", "angle": "Agents remediate accessibility failures across all pages consistently and at scale.", "objection": "Fixing accessibility across every page is overwhelming.", "reframe": "Overwhelming by hand, routine for an agent — it applies the required fixes across every page consistently while your team spot-checks, which is how you meet the legal deadline.", "personaShift": { "CRO": "meets the accessibility mandate", "CFO": "avoids legal exposure", "CTO": "remediates at scale", "VPE": "spares a soul-crushing manual slog" } },
  { "tier": 2, "prompt": "New rules require us to log and retain every data access, which our systems don't do.", "pattern": "Access-logging mandate", "rootCause": "Systems lack the comprehensive access logging regulation now requires.", "consequence": "Non-compliance and no forensic trail for data access.", "diagnostic": "Could you show a complete record of who accessed what data over the last year?", "angle": "Agents implement consistent access logging and retention across the systems in scope.", "objection": "Adding access logging everywhere is a massive retrofit.", "reframe": "Massive and repetitive — the agent adds consistent access logging across every system, producing the trail the regulation demands without a manual system-by-system effort.", "personaShift": { "CRO": "satisfies the access-logging mandate", "CTO": "implements logging at scale", "CFO": "avoids non-compliance penalties", "VPE": "spares a manual retrofit slog" } },
  { "tier": 3, "prompt": "Our compliance program passes on paper but nobody's verified the controls actually work in code.", "pattern": "Paper-only compliance", "rootCause": "Documented controls aren't verified against actual implementation.", "consequence": "A gap between claimed and real compliance.", "diagnostic": "Have your documented controls been verified against what the code actually does?", "angle": "Agents verify that each documented control is genuinely enforced in the code.", "objection": "Our controls are documented; that's what audits check.", "reframe": "Documentation isn't enforcement — a control on paper can be absent in code. The agent verifies each control against the implementation, closing the gap before an incident or auditor finds it.", "personaShift": { "CRO": "verifies controls actually work", "CTO": "closes the paper-to-code gap", "CFO": "reduces false-assurance risk", "VPE": "confirms enforcement efficiently" } },
  { "tier": 1, "prompt": "A new regulation requires consent management our older apps were never built to support.", "pattern": "Consent-management mandate", "rootCause": "Legacy apps lack the consent controls regulation now requires.", "consequence": "Non-compliant data handling across customer-facing apps.", "diagnostic": "Can your apps prove they captured and honored user consent as required?", "angle": "Agents implement consent capture and enforcement consistently across the apps.", "objection": "Retrofitting consent into all our apps is a huge lift.", "reframe": "The agent applies the consent logic consistently across every app and verifies it — turning a huge manual retrofit into a coordinated, tested rollout.", "personaShift": { "CRO": "meets the consent mandate", "CTO": "retrofits consent at scale", "CFO": "avoids privacy penalties", "VPE": "spares a per-app slog" } },
  { "tier": 4, "prompt": "Legal says any change to a regulated system requires so much sign-off it's not worth automating.", "pattern": "Sign-off-overhead objection", "rootCause": "Heavy approval overhead makes any change seem not worth it.", "consequence": "Necessary compliance changes stall under process weight.", "diagnostic": "Is the sign-off per change, or could a batch of similar changes be approved together?", "angle": "Agents batch similar changes for a single review, so approval overhead is amortized, not multiplied.", "objection": "The sign-off overhead makes automating changes pointless.", "reframe": "The overhead is per-decision, not per-line. The agent groups similar changes so one review covers many — the sign-off is amortized across the batch, not repeated for each.", "personaShift": { "CRO": "keeps approval rigor intact", "CTO": "amortizes review overhead", "CFO": "reduces cost per compliant change", "VPE": "removes per-change friction" } },
  { "tier": 2, "prompt": "A regulator now requires us to demonstrate data lineage we've never been able to trace.", "pattern": "Data-lineage mandate", "rootCause": "No ability to trace how data flows and transforms end to end.", "consequence": "Can't demonstrate lineage the regulation requires.", "diagnostic": "Could you trace a data element from origin to report to satisfy a regulator?", "angle": "Agents trace data lineage through the systems and produce the required documentation.", "objection": "Tracing lineage across all our systems is beyond us.", "reframe": "The agent follows the data through the code and pipelines to build the lineage map — the exhaustive tracing that's infeasible manually is exactly its strength.", "personaShift": { "CRO": "demonstrates required data lineage", "CTO": "makes data flows traceable", "CFO": "avoids lineage-related penalties", "VPE": "spares a manual tracing effort" } }
];
